drivers/mmc/core/mmc.c

udev probes this but it can't be read like a normal disk.
The excessive errors generated cause udev to bail out during boot.
FIXME: fix udev?
[endlessm/eos-shell#4438]

MMC: don't create rpmb partition node

---

drivers/net/usb/huawei_cdc_ncm.c
drivers/usb/serial/option.c

Two fixes from upstream also included in Ubuntu's 3.13 trusty kernel. The first one fixes an issue with communication on Huawei modems while the second just suppresses some incorrect error messages in the journal.
[endlessm/eos-shell#4248]

Fix huawei modem communication

---

Documentation/kernel-parameters.txt
drivers/input/serio/i8042-x86ia64io.h
drivers/input/serio/i8042.c

pulling in patch from https://bugzilla.kernel.org/show_bug.cgi?id=81331 to fix Elantech trackpads
[endlessm/eos-shell#4607]

Input: i8042 - reset keyboard to fix Elantech touchpad detection

---

drivers/input/serio/i8042-x86ia64io.h

Commit 209285518bef4b3 added a fix for Gigabyte P35V2, but not P35V1. This adds
that model to the list which recieve the fix.
[endlessm/eos-shell#4607]

Input: 18042 - add Gigabyte P35v1 to Elantech touchpad fix

---

drivers/gpu/drm/i915/i915_drv.c
ubuntu/i915/i915_drv.c

This reverts commit 713b616949f9ed8f903458c5284e1351d378e222.
The i915_bdw driver takes 1 second longer to load during boot (1.7s vs 0.7s).
https://github.com/endlessm/eos-shell/issues/4701

Revert "UBUNTU: SAUCE: Switch VLV/BYT to use i915_bdw."

---

drivers/net/ethernet/realtek/r8169.c

Match new BIOS version that fixes #4646
[endlessm/eos-shell#4648]

r8169: Match new BIOS version

---

drivers/acpi/video.c

Now that we're hoping to have resolved all of the problems with
video.use_native_backlight=1, make that the default at last.
Link: http://marc.info/?l=linux-acpi&m=139716088401106&w=2
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
https://github.com/endlessm/eos-shell/issues/4728

ACPI / video: Change the default for video.use_native_backlight to 1

---

drivers/platform/x86/classmate-laptop.c

The WiFi media button on the NL3 reports keycodes 0x8b and 0x9b to the
platfrom driver. Fix the classmate-laptop driver to support these codes.
[endlessm/eos-shell#4792]

x86/platform: add WiFi media button support for NL3

---

drivers/gpu/drm/i915/intel_dp.c

This is a workaround to fix the black screen problem and i915 driver
crashing on the NL3 laptop when switching to an external display. This
fix is to be intended as a dirty hack before upgrading to a new kernel
where it is possible to include the real fix (torvalds/linux@83b8459)
[endlessm/eos-shell#4649]

drm/i915: do not force VDD when switching panel off

---

sound/pci/hda/patch_realtek.c

[endlessm/eos-shell#4856]
Signed-off-by: Carlo Caione <carlo@endlessm.com>

ALSA: hda - retask headphone jack as 'Dock Headphone Jack'

---

sound/pci/hda/patch_realtek.c

To have both the audio jacks working at the same time on the NL3 laptop
we need to force ALSA to set the 'Auto-Mute Mode' mixer control to
'Speaker only'.  This patch adds a new fixup specific for the NL3 laptop
to force this setting.
[endlessm/eos-shell#4990]

ALSA/hda: add new fixup for the automute on NL3 laptop

---

drivers/block/loop.c
drivers/md/bitmap.c
drivers/md/md.c
drivers/usb/gadget/f_mass_storage.c
drivers/usb/gadget/storage_common.c
fs/binfmt_elf.c
fs/coredump.c
fs/ext4/super.c
fs/file_table.c
fs/open.c
fs/proc/base.c
fs/proc/fd.c
fs/proc/nommu.c
fs/proc/task_mmu.c
fs/proc/task_nommu.c
fs/seq_file.c
include/linux/fs.h
include/linux/seq_file.h
kernel/events/core.c
mm/memory.c
mm/swapfile.c

Overlayfs stores the incorrect path to files in struct file because the
real files are references to private mounts of the real directories
within the overlay.
This adds support for a separate struct path in struct file that's used
when the requested path covers the real path. Some helpers are added to
make usage of the covering path transparent.
This is based on a patch from Miklos Szeredi [1] that was rejected
upstream. This patch is a temporary workaround until a solution is
agreed to upstream.
1. https://lkml.org/lkml/2015/3/20/372
[endlessm/eos-shell#5001]

fs: Add covering path support for overlayfs

---

drivers/pinctrl/intel/pinctrl-cherryview.c

BIOS/platform may use some of the pins by themselves, such as providing SCI
(System Control Interrupt) from the embedded controller. The driver masks
all interrupts at probe time which prevents those pins from triggering
interrupts properly.
Fix this by not masking all interrupts at probe -- it should be enough just
to clear the status register.
Reported-by: Yu C Chen <yu.c.chen@intel.com>
Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>
This patch fixes the problems with the ASUS E202SA brightness keys. It
was not included upstream and the relevant discussion can be found at
https://lkml.org/lkml/2015/5/22/111
[endlessm/eos-shell#5342]

pinctrl: cherryview: Do not mask all interrupts on probe

---

drivers/platform/x86/Kconfig
drivers/platform/x86/Makefile
drivers/platform/x86/asus-wrc.c

Some ASUS notebooks like the E202SA have a separate ACPI for
notifications from the airplane mode hotkey. This device is called ASHS
in the DSDT and its ACPI _HID is ATK4002.
[endlessm/eos-shell#5455]

platform/x86: Add ASUS Wireless Radio Control driver

---

sound/pci/hda/patch_realtek.c

The hda auto parser has a fixup that is enabled by default to
try to detect when a supposed headphone jack is actually a
line out jack. The change to set the other headphone jack to
a 'Dock Headphone Jack' changed the sequence number of that
jack to the correct value of 0xf; however, the front jack still
gets an incorrect value from the hardware. This makes the auto
parser fixup conclude the front jack is not really a headphone
jack.
Disable that erroneous fixup to allow more than one headphone
jack to be detected without changing one to a line out jack.
[endlessm/eos-shell#5358]

ALSA/hda: add fixup to not treat second headphone jack as line out

---

net/rfkill/core.c

When switching the state of all RFKill switches of type all we need to
replicate the RFKILL_TYPE_ALL global state to all the other types global
state, so it is used to initialize persistent RFKill switches on
initialization.
[endlessm/eos-shell#5598]

rfkill: Copy "all" global state to other types

---

drivers/pci/quirks.c

In the default configuration, these Asus laptops log a lot of PCIe
AER spam, and this potentially also causes some system instability:
pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected,
type=Physical Layer, id=00e5(Receiver ID)
pcieport 0000:00:1c.5:   device [8086:9d15] error status/mask=00000001/00002000
pcieport 0000:00:1c.5:    [ 0] Receiver Error         (First)
pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected,
type=Physical Layer, id=00e5(Receiver ID)
pcieport 0000:00:1c.5:   device [8086:9d15] error status/mask=00000001/00002000
pcieport 0000:00:1c.5:    [ 0] Receiver Error         (First)
pcieport 0000:00:1c.5: AER: Corrected error received: …

PCI: disable MSI on problematic Asus platforms

---

drivers/gpu/drm/drm_crtc.c

We don't have hi-DPI mode support yet, so just cap userspace to this mode.
[endlessm/eos-shell#5693]

drm: Ignore modes above 1920x1200

---

drivers/gpu/drm/drm_crtc.c

It seems that sometimes, `htotal` / `vtotal` are 0. We want `hdisplay` / `vdisplay` here.
[endlessm/eos-shell#5693]

drm: Fix up hack for 1920x1200

---

drivers/gpu/drm/i915/i915_drv.h
drivers/gpu/drm/i915/intel_display.c
drivers/gpu/drm/i915/intel_drv.h
drivers/gpu/drm/i915/intel_fbc.c

The reverted commit introduces a regression in both the EC-200 (Celeron
N2807) and the ASUS-E202SA (Atom Cherryview), where the screen will
remain black during the whole boot process, until any input action is
performed on X (keypress, cursor movement etc).
[endlessm/eos-shell#5698]

Revert "drm/i915: Use the disable callback for disabling planes."

---

drivers/gpu/drm/i915/intel_display.c

We tried to do this generically in the DRM layer by hiding certain modes from userspace, but it turns out that fbdev is immune from those rules, and everything seemed to just copy over the fbdev mode since it looked mostly OK.
[endlessm/eos-shell#5693]

drm/i915: Hack up max mode sizes to prevent Hi-DPI mode

---

drivers/pci/quirks.c

This laptop has a lot of PCI express error spam in dmesg until pci=nomsi
is used.
pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e5(Receiver ID)
pcieport 0000:00:1c.5:   device [8086:9d15] error status/mask=00000001/00002000
pcieport 0000:00:1c.5:    [ 0] Receiver Error
[endlessm/eos-shell#5745]

PCI: disable MSI on Asus X555UB

---

arch/x86/kernel/tsc.c

After upgrading for 4.2 we started seeing lockups on the ASUS E202SA due
to TSC instability. This commit disables TSC on this laptop.
[endlessm/eos-shell#5687]

tsc: Disable TSC on ASUS E202SA

---

arch/x86/kernel/tsc.c

I've introduced the following warning when fixing #5687 :(
```
arch/x86/kernel/tsc.c: In function ‘check_tsc_quirks’:
arch/x86/kernel/tsc.c:1167:1: warning: no return statement in function returning non-void [-Wreturn-type]
```
@dsd, @carlocaione, @magcius Could one of you guys please review and merge this one?

Fix compiler warning

---

sound/pci/hda/patch_realtek.c

These laptops need a different pin value on pin 0x19 for the headset
microphone to work. Unfortunatelly I could not find a way to make jack
detection for the headset microphone to work.
[endlessm/eos-shell#5769]
[endlessm/eos-shell#5770]

sound/hda: Add pin quirk for ASUS X540SA/X555UB headset mic

---

drivers/input/serio/i8042.c

On this model, any time the self test command is sent to the
i8042 controller the trackpad stops sending data. Never send the
self test command when this model is detected with DMI.
[endlessm/eos-shell#5681]

Input: i8042 - don't run self test on Asus X455LAB

---

drivers/net/wireless/rtlwifi/rtl8188ee/hw.c
drivers/net/wireless/rtlwifi/rtl8192ee/hw.c
drivers/net/wireless/rtlwifi/rtl8723ae/hw.c
drivers/net/wireless/rtlwifi/rtl8723be/hw.c
drivers/net/wireless/rtlwifi/rtl8821ae/hw.c

This reverts commit 1277fa2ab2f9a624a4b0177119ca13b5fd65edd0.
This commit is causing a softlockup during downloads with a RTL8821AE
WiFi card. This is the stack dump:
CPU: 0 PID: 1108 Comm: wget Not tainted 4.2.0 #28
Hardware name: ASUSTeK COMPUTER INC. E202SA/E202SA, BIOS 18/2015
task: e7b92200 ti: f3d28000 task.ti: f3d28000
EIP: 0060:[<c127ec02>] EFLAGS: 00200202 CPU: 0
[<c19329be>] tcp_v4_rcv+0x71e/0x8f0
EIP is at queued_spin_lock_slowpath+0x192/0x1b0
EAX: 00000101 EBX: 00000101 ECX: f3fe1320 EDX: 00000001
ESI: 00000101 EDI: 00000001 EBP: f3d29e14 ESP: f3d29e04
DS: 007b ES: 007b FS: 00d8 GS: 0033 SS: 0068
CR0: 8005003b CR2: a9f78000 CR3: 2eb52000 CR4: 001006d0
Stack:
00000101 00000001 f3d29ed0
[<c195f08a>] ? iptable_filter_hook+0x2a/0x80
[<c190ff3c>] ip_local_deliver_finish+0x6c/0x1f0 …

Revert "rtlwifi: Remove the clear interrupt routine from all drivers"

---

drivers/idle/intel_idle.c

Enabling Skylake C-states on the Asus N552VW results in a hang on
boot. Disable idle states when this laptop is detected with DMI.
[endlessm/eos-shell#6069]

intel_idle: Disable on Asus N552VW

---

drivers/bluetooth/ath3k.c
drivers/bluetooth/btusb.c

Add Atheros usb bluetooth hw id (0x13d3:0x3487) to
ath3k's device list and btusb's device blacklist to
have the device recognized and the correct module loaded.
Without this, only the generic btusb module is loaded and
bluetooth doesn't work.
[endlessm/eos-shell#6103]

eos-shell#6103 Bluetooth Atheros 0x13d3:0x3487

---

debian.master/control.stub.in

Our build infrastructure (Jenkins) do not support BuildProfileSpec or
stage markup yet.
[endlessm/eos-shell#6228]

Packaging: remove control markup for stage1

---

sound/soc/intel/boards/cht_bsw_rt5645.c

ASoC: cht_bsw_rt5645: Fix writing to string literal

---

drivers/platform/x86/ideapad-laptop.c

Pressing a key to turn radios off should emit KEY_RFKILL instead of
KEY_WLAN.
https://phabricator.endlessm.com/T10942

T10942: ideapad_laptop: Makes radio ON/OFF key emit KEY_RFKILL

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The Asus N552VW has two video cards (Intel+NVIDIA), we only really use
the Intel one, but the NVIDIA keeps running, raising the machine's
temperature, triggering the fan at full speed, wasting energy, and
sending a lot of errors to the kernel log.
Disable it for now, and revisit later for a proper fix, as some future
machines might depend on it.
https://phabricator.endlessm.com/T11116

T11116: config: Disable nouveau on the Asus N552VW

---

drivers/i2c/busses/i2c-designware-platdrv.c

The Lenovo Yoga 900 i2c needs a non-zero sda_hold_time in order to work
properly. The correct solution is to have this passed by intel-lpss,
which is what happens on Linux 4.5 and what we have backported to be
released on EOS 2.7. For EOS 2.6 we are providing DMI quirk instead of
backporting the whole series from Linux 4.5 (16 patches).
The solution provided here was taken from a test patch provided for the
original reporter of this problem on
http://www.spinics.net/lists/linux-i2c/msg22055.html
https://phabricator.endlessm.com/T1103

i2c: Hardcode sda_hold_time for Lenovo Yoga 900

---

drivers/platform/x86/asus-nb-wmi.c

This fixes the airplane-mode indicator LED for the N552VW, X456UA and X456UF Asus laptops.
https://phabricator.endlessm.com/T11110

T11110 for eos2.6: airplane-mode indicator LED fixes

---

drivers/gpu/drm/i915/i915_drv.c

NOTE FOR FUTURE REBASE: squash this commit on the one introducing the
problem, so we don't have a broken build in our history (which makes
bisects harder).
This fixes a problem introduced by
9c3df35 Revert "UBUNTU: SAUCE: i915_bpo: Support only SKL, KBL and BXT with the backport driver"
which breaks our build with
In file included from /usr/src/packages/BUILD/linux-4.4.0/include/drm/i915_drm.h:29:0,
from /usr/src/packages/BUILD/linux-4.4.0/drivers/gpu/drm/i915/i915_drv.c:33:
/usr/src/packages/BUILD/linux-4.4.0/drivers/gpu/drm/i915/i915_drv.c:439:21: error: 'intel_kabylake_info' undeclared here (not in a function)
INTEL_KBL_GT1_IDS(&intel_kabylake_info),
^
/usr/src/packages/BUILD/linux-4.4.0/include/drm/i915_pciids.h:42:18: note: in definition of macro 'INTEL_VGA_DEVICE'
(unsigned long) …

T10839: Fix build

---

drivers/hid/i2c-hid/i2c-hid.c

When an i2c-hid device is resumed from system sleep the driver resets
the device to be sure it is in known state. The device is expected to
issue an interrupt when reset is complete.
This reset might take few milliseconds to complete so if the HID driver
on top (hid-rmi) starts to set up the device by sending feature reports
etc. the device might not issue the reset complete interrupt anymore.
Prevent sending of feature/output reports while the device is being
reset by adding a mutex which is held during that time.
https://phabricator.endlessm.com/T11082

T11082: Fix race between i2c-hid and hid-rmi on Yoga 900

---

drivers/hid/i2c-hid/i2c-hid.c

When an i2c-hid device is resumed from system sleep the driver resets
the device to be sure it is in known state. The device is expected to
issue an interrupt when reset is complete.
This reset might take few milliseconds to complete so if the HID driver
on top (hid-rmi) starts to set up the device by sending feature reports
etc. the device might not issue the reset complete interrupt anymore.
Prevent sending of feature/output reports while the device is being
reset by adding a mutex which is held during that time.
https://phabricator.endlessm.com/T11082

T11082-eos2.6: Fix race between i2c-hid and hid-rmi on Yoga 900

---

debian/control-scripts/postinst

We always shipped dracut as the initramfs generator, but previously
with a update-intramfs wrapper script. On the last dracut update we
decided to drop this wrapper and fix packages use of dracut.
https://phabricator.endlessm.com/T11096

Debian: Stop using update-initramfs

---

drivers/gpu/drm/radeon/radeon_display.c
drivers/gpu/drm/radeon/radeon_fb.c

Move all the logic to radeon_fb.c and add checks to functions
called frome elsewhere.
bug:
https://bugzilla.kernel.org/show_bug.cgi?id=112781
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>

drm/radeon: rework fbdev handling on chips with no connectors

---

drivers/platform/x86/ideapad-laptop.c

Don't try to control the touchpad on laptops that do not support it, as
it leads to sending wrong KEY_TOUCHPAD_ON / KEY_TOUCHPAD_OFF events to
userspace.
https://phabricator.endlessm.com/T11369

ideapad: DMI quirk for touchpad control

---

arch/x86/boot/compressed/eboot.c
arch/x86/kernel/kexec-bzimage64.c
drivers/acpi/apei/einj.c
drivers/acpi/osl.c
drivers/char/mem.c
kernel/power/user.c

Backport Matthew Garrett's securelevel framework to prevent malicious users or hardware / firmware to disable secure boot and potentially chainload another OS or bootloader.
https://phabricator.endlessm.com/T12101

T12101: Restrict more kernel functionality when secure booted

---

kernel/power/user.c

Fix missing include.
https://phabricator.endlessm.com/T12101

fixup! uswsusp: Disable when module signing is enforced

---

drivers/pci/quirks.c

pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected,
type=Physical Layer, id=00e5(Receiver ID)
pcieport 0000:00:1c.5:   device [8086:9d15] error status/mask=00000001/00002000
pcieport 0000:00:1c.5:    [ 0] Receiver Error         (First)
avoid this with adding a quirk for X541UV

PCI: disable MSI on problematic ASUS X541UV

---

sound/pci/hda/patch_realtek.c

ASUS X441SA with ALC3236 (ALC223) codec requires the known fixup
(ALC269_FIXUP_HEADSET_MIC) and a different pin value on pin 0x19
for making the headset mic working.

Sound: hda - Fix headset support for ASUS X441SA

---

drivers/hid/hid-multitouch.c

commit 73e7d63efb4d774883a338997943bfa59e127085 upstream.
as reported by https://bugzilla.kernel.org/show_bug.cgi?id=108481
This bug reports mentions 6d4f5440 ("HID: multitouch: Fetch feature
reports on demand for Win8 devices") as the origin of the problem but this
commit actually masked 2 firmware bugs that are annihilating each other:
The report descriptor declares two features in reports 3 and 5:
0x05, 0x0d,                    // Usage Page (Digitizers)             318
0x09, 0x0e,                    // Usage (Device Configuration)        320
0xa1, 0x01,                    // Collection (Application)            322
0x85, 0x03,                    //  Report ID (3)                      324
0x09, 0x22,                    //  Usage (Finger)                     326
0xa1, 0x00, …

HID: multitouch: fix input mode switching on some Elan panels

---

drivers/gpu/drm/i915/intel_display.c

Similar to https://bugs.freedesktop.org/show_bug.cgi?id=96321.
ASUS X441SA does not probe displayPort on Port B. The displayPort is
connected to the external VGA connector, thus the external VGA is not
functional. This is a temporary workaround.
https://phabricator.endlessm.com/T12353

i915: Force DP probe Port B on ASUS X441SA

---

debian/rules
debian/rules.d/0-common-vars.mk

This is used by cross-toolchain-base, which is needed to build
cross-compilers.
https://phabricator.endlessm.com/T10613

config: Build linux-source with contents

---

ubuntu/i915/intel_opregion.c

Machines that use Ubuntu provided display drivers are currently
vulnerable to the bug described in commit 3f713ab66. This applies commit 3f713ab66 to the Ubuntu provided i915 drivers.
https://phabricator.endlessm.com/T12709
Signed-off-by: Benjamin Antin <ben.antin@endlessm.com>

ubuntu/i915: Apply patch for large number of ACPI display devices

---

sound/pci/hda/patch_realtek.c

We have Acer laptop Aspire E5-475 with codec ALC255 which can't
detect headset mic, after adding pin definitions in pin quirk table,
the headset mic can be detected and work.
https://phabricator.endlessm.com/T12912

Sound/hda: add new pin definition pin quirk table for Acer Laptops

---

ubuntu/vbox/vboxvideo/vbox_ttm.c

This applies the fix pointed in
https://www.virtualbox.org/ticket/15769#comment:4

vbox: Fix kernel panic after installing guest additions

---

drivers/bluetooth/btrtl.c
drivers/bluetooth/btusb.c

Realtek ships certain bluetooth USB devices which report themselves as
standard USB bluetooth devices, but which require special drivers.
Here we add support for the Realtek 8723BE devices shipped in the
Foxconn MT13.
https://phabricator.endlessm.com/T12741
Signed-off-by: Benjamin Antin ben.antin@endlessm.com

Bluetooth: Add Realtek support for Foxconn MT13

---

sound/pci/hda/patch_realtek.c

This fixes headphone jack sensing and enables use of the internal
microphone. It's verified on Asus E402NA.
https://phabricator.endlessm.com/T13185

sound/hda: ALC256 mic and headset-mode fixups for Asus laptops

---

ubuntu/i915/intel_ddi.c
ubuntu/i915/intel_display.c
ubuntu/i915/intel_drv.h

So far we configured a static lane latency optimization during driver
loading/resuming. The specification changed at one point and now this
configuration depends on the lane count, so move the configuration
to modeset time accordingly.
It's not clear when this lane configuration takes effect. The
specification only requires that the programming is done before enabling
the port. On CHV OTOH the lanes start to power up already right after
enabling the PLL. To be safe preserve the current order and set things
up already before enabling the PLL.
v2: (Ander)
- Simplify the optimization mask calculation.
- Use the correct pipe_config always during the calculation instead
of the bogus intel_crtc->config.
CC: Ander Conselvan de Oliveira <ander.conselvan.de.oliveira@intel.com>
Bugzilla: …

drm/i915/bxt: Set DDI PHY lane latency optimization during modeset

---

ubuntu/i915/i915_dma.c
ubuntu/i915/i915_drv.h
ubuntu/i915/intel_atomic.c
ubuntu/i915/intel_display.c
ubuntu/i915/intel_drv.h
ubuntu/i915/intel_pm.c

This patch series solves an issue where hotplugging HDMI would give a corrupted display, and a system freeze on hot-unplug.
A small number of commits needed small tweaks for this backport, noted that in the commit message of each one.
https://phabricator.endlessm.com/T13389

Fix Apollo Lake HDMI hotplug

---

drivers/input/serio/i8042.c

The self-test command causes the trackpad on this model to stop
reporting. Add DMI quirk for the Z540LA so we don't send the self test
command.
Signed-off-by: Benjamin Antin <ben.antin@endlessm.com>
https://phabricator.endlessm.com/T13468

Input: i8042 - don't run self test on Asus Z450LA

---

debian.master/control.d/flavour-control.stub

We intend to created linux-signed-image packages with kernels signed for
UEFI. These packages are identical to the unsigned linux-images but with
the vmlinuz file signed. In order to let these new packages install
correctly, they need to conflict with the normal unsigned packages.
Likewise, the linux-image-extra modules packages need to allow them as
an alternate dependency.
https://phabricator.endlessm.com/T12944

debian: Allow installation of signed linux-image packages

---

drivers/mfd/intel-lpss-pci.c

The I2C arbitration lost erros happens on ASUS Apollolake models
(on E402NA and E403NA) with ELAN touchpad and it requires programming
non-zero SDA hold time. Tried the Skylake I2C SDA hold time and clock
rate which fixed similar issue on Lenovo Yoga 900. It works fine w/o
problem.
Error messages are as following.
i2c_designware i2c_designware.1: i2c_dw_handle_tx_abort: lost arbitration
hid (null): reading report descriptor failed
i2c_hid i2c-ELAN1200:00 can't add hid device: -5
i2c_hid: probe of i2c-ELAN1200:00 failed with error -5
https://phabricator.endlessm.com/T13616

mfd: intel-lpss: Pass I2C SDA hold time to controller driver on APL

---

drivers/mfd/intel-lpss-acpi.c
drivers/mfd/intel-lpss-pci.c

This fixes a build error, and should be squashed on the commit that
creates the problem on a future rebase.

fixup! mfd: intel-lpss: Add default I2C device properties for Lake

---

include/linux/shmem_fs.h
mm/shmem.c

For the reasons discussed at
<http://www.spinics.net/lists/linux-mm/msg109982.html>, this simplistic
implementation of user xattrs can't simply be made available to
everyone.
We want user xattrs on tmpfs to support flatpak running as an
unprivileged user on overlayfs whose upper fs is tmpfs, a situation
which only arises in our pristine image boots. So, for our purposes, a
mount flag is okay: we can set it at the same time as setting up the
overlays.
This is a forward-port of #179.
https://phabricator.endlessm.com/T13817

tmpfs: add user_xattr mount option

---

drivers/platform/x86/asus-nb-wmi.c

The Asus UX360CAK/UX360UA has airplane-mode indicator LED and the WMI
WLAN user bit set, so asus-wmi uses ASUS_WMI_DEVID_WLAN_LED (0x00010002)
to store the wlan state, which has a side-effect of driving the airplane
mode indicator LED in an inverted fashion. quirk_no_rfkill prevents
asus-wmi from registering RFKill switches at all for this laptop and
allows asus-wireless to drive the LED through the ASHS ACPI device.
https://phabricator.endlessm.com/T13916
Signed-off-by: Chris Chiu chiu@endlessm.com

asus-wmi: Add quirk_no_rfkill for the Asus UX360CAK/UX360UA

---

drivers/hid/hid-multitouch.c

According to https://msdn.microsoft.com/en-us/library/windows/hardware/mt604195(v=vs.85).aspx
external buttons have some weird usage mapping:
- Button 2 Indicates Button State for external button for primary
(default left) clicking.
- Button 3 Indicates Button State for external button for secondary
(default right) clicking.
So in the current state, the buttons are mapped to right and middle.
Move the usage by one to correctly map the external buttons.
Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>

HID: multitouch: handle external buttons for Precision Touchpads

---

drivers/mmc/host/sdhci-acpi.c

Add an entry for the SDIO bus in the ECS EF20 cherry trail laptop:
Device (SDHB) {
Name (_ADR, 0x00110000)
Name (_HID, "80860F14" /* Intel Baytrail SDIO/MMC Host Controller */)
Name (_CID, "PNP0D40" /* SDA Standard Compliant SD Host Controller */)
Name (_DDN, "Intel(R) SDIO Controller - 80862295")
Name (_UID, 0x02)
Name (_HRV, One)
A SDHB device with the same _HID and _UID can also be found on other
cherry trail products like Chuwi Hi10.
Signed-off-by: Daniel Drake <drake@endlessm.com>
https://phabricator.endlessm.com/T6305

mmc: sdhci-acpi: support 80860F14 UID 2 SDIO bus

---

drivers/bluetooth/hci_bcm.c

Add the BCM2E96 ID used by the ECS EF20 laptop.
hci0: BCM: chip id 82
hci0: BCM43341B0 (002.001.014) build 0000
hci0: BCM (002.001.014) build 0158
According to the vendor kernel, the GPIOs to use here are ordered
differently from the way this driver behaves as standard.
We also apply the modified order for this product.
It might be more correct to modify the BIOS to list the correct order,
although a comment in the vendor kernel suggests that this change
may be standard for all BCM2E96 devices.
Bluetooth seems to work on EF20 with or without this, but I think it's
working more reliably with this change and also the host wakeup
interrupts are now arriving.
https://phabricator.endlessm.com/T10572
Signed-off-by: Carlo Caione <carlo@endlessm.com>

Bluetooth: hci_bcm: Add BCM2E96 device and fix GPIOs for EF20EA

---

drivers/platform/x86/asus-nb-wmi.c

Apply the quirk_no_rfkill for Asus UX430UQ has airplane-mode indicator.
It prevents asus-wmi from registering RFKill switches at all and allows
asus-wireless to drive the LED through the ASHS ACPI device.
https://phabricator.endlessm.com/T14464

asus-wmi: Add quirk_no_rfkill for the Asus UX430UQ

---

drivers/hid/i2c-hid/i2c-hid.c

It may be necessary to allocate bigger buffers in i2c_hid_start() if the
report size of a device is bigger than the buffers allocated on probe.
When this happens ihid->irq is already running, so it needs to be
disabled otherwise ihid->inbuf may be modified after freed if
i2c_master_recv() in i2c_hid_get_input() is called immediatelly before
i2c_hid_free_buffers() in i2c_hid_start().
This problem has been observed on an Asus UX360UA laptop which has an
I2C touchpad, and this change makes the problem go away.
https://phabricator.endlessm.com/T14091

i2c-hid: Disable IRQ before freeing buffers

---

drivers/platform/x86/asus-nb-wmi.c

Apply the quirk_no_rfkill for the same inverted airplane mode indicator
issue on Asus X555UQ, X756UQK, X756UXK, X756UWK, X756UAK, G502VSK,
G702VSK, G702VMK
https://phabricator.endlessm.com/T14464
https://phabricator.endlessm.com/T14360

asus-wmi: Add quirk_no_rfkill for more Asus laptops

---

drivers/net/wireless/ath/ath9k/hw.c

The Acer Aspire ES1-421 rfkill_gpio seems connet to something
unknown. The NFA335 module can work on first boot, then goes to
hardware-disabled after suspend/resume. And itt doesn't come back
even after reboot. This commit ignore the rfkill_gpio input based
on DMI info.
https://phabricator.endlessm.com/T14777

ath9k: add a norfkill_gpio quirk for Acer Aspire ES1-421

---

drivers/platform/x86/acer-wmi.c

The same method to activate LM(Launch Manager) can also be used to
activate the RF Button driver with different bit toggled in the same
lm_status. To express that many functions this byte field can achieve,
rename the lm_status to app_status. And also the app_mask is the bit
mask which specifically indicate which bits are going to be changed.
Add acer_wmi_enable_rf_button() to activate the RF button driver. It
will send scancode or inform EC that the airplane mode hotkey has been
pressed.
https://phabricator.endlessm.com/T14825

acer-wmi: Inform BIOS/EC that RF Button Driver is activated

---

drivers/pci/quirks.c

It's also a Realtek RTL8821AE card on Skylake which cause PCIe AER
error spam. However, it happen on different PCIe root port.
pcieport 0000:00:1c.7: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e5(Receiver ID)
pcieport 0000:00:1c.7:   device [8086:a117] error status/mask=00000001/00002000
pcieport 0000:00:1c.7:    [ 0] Receiver Error
pcieport 0000:00:1c.7: AER: Corrected error received: id=00e5
pcieport 0000:00:1c.7: can't find device of ID00e5
pcieport 0000:00:1c.7: AER: Corrected error received: id=00e5
pcieport 0000:00:1c.7: can't find device of ID00e5
Apply the same workaround quirk_disable_rtl_aspm() on the problematic
PCI vendor/device ID.

PCI: Disable AER for Skylake+Realtek systems on ASUS D520MT-K

---

drivers/platform/x86/acer-wmi.c

Use acpi_dev_found() before acpi_get_devices() if the particular
ACPI device not even exist. On the Acer TravelMate P449-G2-MG we
have observed the acpi_get_devices() here causes the system hang.
There's no such accel device on the machine and it does not happen
on other Acer machines in my hands. Additional check without
function change should be good to have.
https://phabricator.endlessm.com/T15061
Signed-off-by: Chris Chiu <chiu@endless.com>

acer-wmi: Use acpi_dev_found() in acer_wmi_get_handle()

---

drivers/mmc/host/sdhci-pci-core.c

We found the Intel SD Host controller(5acc) fail to switch to HS200
mode on Acer ApolloLake models. So the internal emmc storage can not
be detected. Add SDHCI_QUIRK2_BROKEN_HS200 for particular subsystem
vendor/device id
https://phabricator.endlessm.com/T14845

sdhci-pci: use SDHCI_QUIRK2_BROKEN_HS200 for Acer ApolloLake models

---

drivers/gpu/drm/i915/i915_drv.c
drivers/gpu/drm/i915/i915_drv.h
drivers/gpu/drm/i915/intel_bios.c
drivers/gpu/drm/i915/intel_dp.c

The Weibu F3C has a VGA port, enabled through an onboard PS8613
DP-to-VGA converter chip.
However the BIOS describes the DP interface from the SoC as being
hooked up to an internal 1366x768 LCD panel over eDP, with a backlight.
Until we get a fixed BIOS, force it to be detected as DP. That way
we ignore the panel definition, don't register a backlight device,
and we request the EDID over the AUX pins in order to get display modes.
We also have a problem with presence detection and hotplug. The SoC
detects the DP connection as always connected (since the chip is always
there). The PS8613 does have a DP_HPD pin that looks like it could tell
us when the VGA monitor is present and hotplugged, but we don't know how
that is hooked up to the SoC.
In order to work around this limitation, we poll …

i915: quirk Weibu F3C DP-to-VGA setup

---

sound/pci/hda/patch_realtek.c

ASUS AIO ZN270IE with ALC256 has no audio ouput for internal speaker
and headphone. It require GPIO 2 as an amp. This commit apply the
HDA verb to enable GPIO2 and pull it high.
https://phabricator.endlessm.com/T15562

Sound: hda - Fix speaker support for ASUS AIO ZN270IE

---

drivers/firmware/efi/reboot.c

Some particular Acer/Packard Bell machines hang during shutdown.
It hangs while doing bit operations for turning on SLP_EN bit in
ACPI PM1A control address and Sleep Control Register. Thus the
normal acpi_power_off path can never complete the shutdown process.
This commit offers a quirk for these particular models to do
efi_power_off() instead of normal acpi_power_off() until we find
the root cause.
https://phabricator.endlessm.com/T14785

x86/reboot: Add EFI power off quirk for some particular models

---

drivers/idle/intel_idle.c

This reverts commit 983d29bce13fbc64135fa4650f87ba42d5e16a14.
https://phabricator.endlessm.com/T15710

Revert "intel_idle: Disable on Asus N552VW"

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The Asus GL552VXK/X550VXK/K401UQK has two video cards (Intel+NVIDIA). They
suffer the same runtime pm problem as X756UQK but it happens during boot
from HDD/USB. Apply the same quirk until there's a upstream fix
https://phabricator.endlessm.com/T15697

drm/nouveau: Disable runtime pm on more Asus laptops

---

drivers/pci/quirks.c

Apply the quirk_disable_rtl_aspm for the same combination found in
ASUS D320SF-K.
pcieport 0000:00:1c.0: PCIe Bus Error: severity=Corrected, type=Physical La
yer, id=00e0(Receiver ID)
pcieport 0000:00:1c.0:   device [8086:a115] error status/mask=00000001/0000
2000
pcieport 0000:00:1c.0:    [ 0] Receiver Error
pcieport 0000:00:1c.0: AER: Corrected error received: id=00e0
pcieport 0000:00:1c.0: can't find device of ID00e0
pcieport 0000:00:1c.0: AER: Corrected error received: id=00e0
pcieport 0000:00:1c.0: can't find device of ID00e0
https://phabricator.endlessm.com/T15946

PCI: Disable AER for Skylake+Realtek systems

---

debian.master/control.d/flavour-control.stub

Add a version to the -extra package dependency on -signed-image. When secure boot is enabled, it's not possible to load the modules in a kernel build at a different time because a different transient module signing key is used for each build.
https://phabricator.endlessm.com/T16069

T16069: version the dependency between -extra and -signed-image

---

drivers/pci/quirks.c

Apply the quirk_disable_rtl_aspm for RTL8821AE on Kabylake PCI bridge
in ASUS X550VX. It whould cause lots of applications not responding.
pcieport 0000:00:1c.2: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e2(Receiver ID)
pcieport 0000:00:1c.2:   device [8086:a112] error status/mask=00000001/00002000
pcieport 0000:00:1c.2:    [ 0] Receiver Error
pcieport 0000:00:1c.2: AER: Corrected error received: id=00e2
pcieport 0000:00:1c.2: can't find device of ID00e2
pcieport 0000:00:1c.2: AER: Corrected error received: id=00e2
pcieport 0000:00:1c.2: can't find device of ID00e2
https://phabricator.endlessm.com/T16032

PCI: Disable AER for Kabylake+Realtek systems

---

drivers/acpi/ec.c

The boot_ec is handled differently in kernel 4.10 and 4.8. The DMI
quirk in 4002b744054d5d79c302a95ba67562209ce289dd is originally
designed for the ec driver on kernel 4.10. Fix the NULL boot_ec
and keep the DMI quirk working.
https://phabricator.endlessm.com/T16834

ACPI / EC: Fix NULL reference of boot_ec caused by the DMI quirk

---

drivers/acpi/ec.c

Apply the same DMI quirk in last commit to fix the incorrect GPE number
defined in DSDT on EC device for Asus X580VD
https://phabricator.endlessm.com/T16722

ACPI / EC: Fix media keys not working problem on some Asus X580VD

---

drivers/gpu/drm/nouveau/nvkm/subdev/fb/Kbuild
drivers/gpu/drm/nouveau/nvkm/subdev/fb/gm200.c
drivers/gpu/drm/nouveau/nvkm/subdev/fb/ram.h
drivers/gpu/drm/nouveau/nvkm/subdev/fb/ramgf100.c
drivers/gpu/drm/nouveau/nvkm/subdev/fb/ramgk104.c
drivers/gpu/drm/nouveau/nvkm/subdev/fb/ramgm107.c
drivers/gpu/drm/nouveau/nvkm/subdev/fb/ramgm200.c

As mentioned in https://github.com/skeggsb/linux/commit/6796b129b0e98162a84e0b6322ac28587556d427. 
"drm/nouveau/fb/gm200: split ram implementation from gm107" is Fix for GTX 970 GPUs that are in an odd MMU configuration and it need dependency on 
"drm/nouveau/fb/gf100-: modify constructors to allow more customisation"

T17223 - Fix for GTX 970 GPUs that are in an odd MMU configuration

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The Acer Aspire Z20-730 has two video cards (Intel+NVIDIA), the NVIDIA
(GM108) will hit kernel panic during boot even with the latest nouveau
driver.
Disable it for now, and revisit later for a proper fix, as some future
machines might depend on it.
https://phabricator.endlessm.com/T17225

Disable nouveau on the Acer Aspire Z20-730

---

drivers/platform/x86/acer-wmi.c

If a machine reports a RF Button in the communication button device
bitmap, we need to remove it before calling Get Device Status otherwise
it will return the "Undefined device" (0xE2) error code.
Although this may be a BIOS bug, we don't really need to get or set the
RF Button status. The LED indicator status is controlled by firmware
logic depending on the status of the wireless radios present on the
machine (WiFi, Bluetooth, WWAN).
https://phabricator.endlessm.com/T16187

platform/x86/acer-wmi: Detect RF Button capability

---

drivers/input/serio/i8042-x86ia64io.h

Without this quirk, the touchpad is not responsive on this product, with
the following message repeated in the logs:
psmouse serio1: bad data from KBC - timeout
Add it to the notimeout list alongside other similar Fujitsu laptops.
https://phabricator.endlessm.com/T17627
Signed-off-by: Daniel Drake <drake@endlessm.com>

Input: i8042 - add Fujitsu Lifebook AH544 to notimeout list

---

sound/pci/hda/patch_realtek.c

Acer Aspire U27-880(AIO) with ALC286 codec can not detect headset mic
and internal mic not working either. It needs the similar quirk like
Sony laptops to fix headphone jack sensing and enables use of the
internal microphone.
Unfortunately jack sensing for the headset mic is still not working.
https://phabricator.endlessm.com/T17721

sound/hda: ALC286 mic and headset-mode fixups for Acer Aspire U27-880

---

drivers/bluetooth/btusb.c

This is AZWAVE/AW-CB295NF with Realtek 8822BE which requires a special
driver.
T:  Bus=01 Lev=01 Prnt=01 Port=08 Cnt=03 Dev#=  4 Spd=12   MxCh= 0
P:  Vendor=13d3 ProdID=3526 Rev= 1.10
S:  Manufacturer=Realtek
S:  Product=Bluetooth Radio
S:  SerialNumber=00e04c000001
C:* #Ifs= 2 Cfg#= 1 Atr=e0 MxPwr=500mA
E:  Ad=03(O) Atr=01(Isoc) MxPS=   0 Ivl=1ms
E:  Ad=83(I) Atr=01(Isoc) MxPS=   0 Ivl=1ms
I:  If#= 1 Alt= 1 #EPs= 2 Cls=e0(wlcon) Sub=01 Prot=01 Driver=btusb
E: …

Bluetooth: Add new Realtek 8822BE ID 13d3:3526

---

debian.master/rules.d/armhf.mk

This is a dependency of glibc. We can build the headers/tools/etc
packages without actually building the kernel.
usbip had to be disabled since it depends on a header that we don't
currently ship. It could be enabled in future once we have
"bootstrapped" with this change that will get new headers in place.
https://phabricator.endlessm.com/T17739

Build linux-libc-dev package on ARM

---

drivers/gpu/drm/nouveau/include/nvkm/engine/gr.h
drivers/gpu/drm/nouveau/nvkm/engine/device/base.c
drivers/gpu/drm/nouveau/nvkm/engine/gr/Kbuild
drivers/gpu/drm/nouveau/nvkm/engine/gr/ctxgf100.h
drivers/gpu/drm/nouveau/nvkm/engine/gr/ctxgp102.c
drivers/gpu/drm/nouveau/nvkm/engine/gr/ctxgp107.c
drivers/gpu/drm/nouveau/nvkm/engine/gr/gf100.h
drivers/gpu/drm/nouveau/nvkm/engine/gr/gp100.c
drivers/gpu/drm/nouveau/nvkm/engine/gr/gp107.c
drivers/gpu/drm/nouveau/nvkm/engine/gr/gp10b.c

Forked from GP106 implementation.
Differences:
- 1 PPC/GPC
- Slightly different grctx magics
- dependency of the gr on GP10B

drm/nouveau/gr/gp107: initial support

---

drivers/gpu/drm/nouveau/nvkm/subdev/fb/ramgf100.c

A missing u64 cast causes a 32-Bit wraparound from
4096 MiB to 0 MiB and therefore total 0 MiB VRAM detected
if card has 4096 Mib per FBP.
Signed-off-by: Mario Kleiner <mario.kleiner.de@gmail.com>
Reviewed-by: Karol Herbst <karolherbst@gmail.com>
Signed-off-by: Ben Skeggs <bskeggs@redhat.com>
https://phabricator.endlessm.com/T18047

drm/nouveau/fb/gf100-: Fix 32 bit wraparound in new ram detection

---

drivers/net/wireless/ath/ath10k/hw.h
drivers/net/wireless/ath/ath10k/mac.c

According to the specification "Qualcomm Atheros WLAN SMBIOS 80-Y7674-28
Rev.D", Acer follow it to add a OEM-specific field in SMBIOS to
program the regulatory domain (country code) based on target shipment
country. It basically stores the flag which toggle the 11ac capability,
country code flag and country code ANSI name based on ISO3166-1 alpha2.
This commit read and parse data from SMBIOS and change regulatory
settings while initializing the regulatory domain (country code).
https://phabricator.endlessm.com/T18076

ath10k: initialize regulatory domain based on SMBIOS data

---

sound/pci/hda/patch_realtek.c

The known ALC256_FIXUP_ASUS_MIC fixup can fix the headphone jack
sensing and enable use of the internal microphone on this laptop
X542UN. However, it's ALC294 so create a new fixup named
ALC294_FIXUP_ASUS_MIC to avoid confusion.
https://phabricator.endlessm.com/T17766

sound/hda: ALC294 mic and headset-mode fixups for ASUS X542UN

---

drivers/gpu/drm/nouveau/nouveau_drm.c

https://phabricator.endlessm.com/T18168

nouveau/GP107: Enable noaccel quirk for Acer Aspire A717-71G

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The Asus FX502VD/VE, X580VD and more models with NVIDIA GTX1050(Ti)
has a problem with the interaction between runtime pm and suspend/resume
which leads to the machine hanging on boot/shutdown. This commit
disables runtime pm for all Asus Notebooks with the display chip
NV GP107.
It has to be reverted once if there's a upstream fix.
https://phabricator.endlessm.com/T17322

drm/nouveau: Disable runtime pm on Asus Notebooks with NV GP107

---

drivers/gpu/drm/nouveau/nouveau_drm.c

All laptops ship with NVIDIA GeForce GTX 1050 (Ti) requires passing
'nouveau.noaccel=1' at boot to have it working correctly and avoid
boot or shutdown failure.
With this patch we introduce a new quirk and link it to all Acer
laptops with GP107 to automatically enable this module parameter.
phabricator: https://phabricator.endlessm.com/T18500

Rever old noaccel quirk for Acer A717-71G and enable new quirk for Acer Notebooks

---

drivers/net/wireless/intel/iwlwifi/iwl-drv.c

These messages are not reporting a real error, just the fact that the
firmware knows about more flags than the driver.
Currently these messages are presented to the user during boot if there
is no bootsplash covering the console, even when booting the kernel with
"quiet".
Demoting it to the warn level helps having a clean boot process.

iwlwifi: Demote messages about fw flags size to info

---

drivers/pci/quirks.c

Apply the same quirk_disable_rtl_aspm() for ASUS D830SF which have
the same huge PCIe AER error spam.
https://phabricator.endlessm.com/T18688

PCI: Disable AER for Skylake/Kabylake with Realtek for ASUS D830SF

---

drivers/pci/quirks.c

Realtek cards on Skylake/Kabylake systems cause a huge amount of PCIe
AER error spam. Apply the same quirk_disable_rtl_aspm() for all PCI IDs
of PCI bridge on SKL/KBL.
https://phabricator.endlessm.com/T18753

PCI: Disable AER for Skylake/Kabylake with Realtek wifi cards

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The Acer Aspire Z20-730 has two video cards (Intel+NVIDIA), the NVIDIA
(GM108) will sometimes hit kernel panic during boot and always fail to
resume from suspend.
Disable it for now, and revisit later for a proper fix, as some future
machines might depend on it.
https://phabricator.endlessm.com/T18739

Disable nouveau on the Acer Aspire Z20-780

---

drivers/gpu/drm/nouveau/nouveau_display.c
drivers/gpu/drm/nouveau/nv50_display.c

update vblank state in response to modeset actions and remove call to 
drm_crtc_vblank_off() during unload/suspend. These on()/off() calls should
be done as a result of modesetting actions, and as we shut down all heads
already on unload/suspend, it's pointless to call off() again.

drm/nouveau/kms: pdate vblank state in response to modeset actions and remove call to  drm_crtc_vblank_off() during unload/suspend.

---

sound/pci/hda/patch_realtek.c

The ASUS laptop GL503VM with ALC295 can't detect the headset
microphone until we modify a pin definition.
https://phabricator.endlessm.com/T18650

ALSA: hda/realtek - Add support for ASUS GL503VM headset mic

---

sound/pci/hda/patch_realtek.c

A line out port given by BIOS doesn't have physical jack and the value
of 0x18 pin is also incorrect. Overriding with the correct values to
disable the line out pin and adds support for the headset microphone
which would not otherwise be visible in the system.
https://phabricator.endlessm.com/T18847

sound/hda: Remove line out and fixup headset-mic on Acer TravelMate P648

---

drivers/net/ethernet/realtek/r8169.c

When suspending the Acer Aspire ES1-732 laptop, it always wakes up 3-4
seconds later for no good reason.
After inspection, it's caused by the enabled WOL feature even without
ethernet cable connected. Suspend/resume would work as expected after
disabling WOL. This commit intruduce a DMI quirk which disable the WOL
for affected models until we find better solution.
https://phabricator.endlessm.com/T16236

r8169: Force disable Wakeup-On-Lan on particular Acer laptops

---

net/mac80211/agg-rx.c
net/mac80211/ht.c
net/mac80211/ieee80211_i.h

BugLink: http://bugs.launchpad.net/bugs/1721777
commit bde59c475e0883e4c4294bcd9b9c7e08ae18c828 upstream.
When an RX BA session is started by the driver, and it has to tell
mac80211 about it, the corresponding bit in tid_rx_manage_offl gets
set and the BA session work is scheduled. Upon testing this bit, it
will call __ieee80211_start_rx_ba_session(), thus deadlocking as it
already holds the ampdu_mlme.mtx, which that acquires again.
Fix this by adding ___ieee80211_start_rx_ba_session(), a version of
the function that requires the mutex already held.
Fixes: 699cb58c8a52 ("mac80211: manage RX BA session offload without SKB queue")
Reported-by: Matteo Croce <mcroce@redhat.com>
Signed-off-by: Johannes Berg <johannes.berg@intel.com>
Signed-off-by: Greg Kroah-Hartman …

mac80211: fix deadlock in driver-managed RX BA session start

---

sound/pci/hda/patch_realtek.c

The Acer Apire E5-575T laptop with codec ALC255 has headset detect
problem and sound recording via internal mic suffers from terrible
background noise.
This patch allows the headset microphone to be used and limits the
gain on the (quite noisy) internal microphone.
https://phabricator.endlessm.com/T19640

ALSA: hda - Fix mic issues on Acer Aspire E5-575T

---

drivers/char/tpm/tpm-interface.c

The TPM on Acer Veriton X4110G shows the following message in the
first resume.
tpm tpm0: A TPM error(38) occured continue selftest
And error(38) is TPM_ERR_INVALID_POSTINIT which means the TPM is
not in the correct state. Then the following suspend will always
fail with the following messages.
tpm tpm0: Error (38) sending savestate before suspend
PM: Device 00:0b failed to suspend: error 38
This commit logs the unexpected TPM state and skip the TPM_SaveState
in following suspends.
https://phabricator.endlessm.com/T20438

tpm: fix suspend failure on Acer Veriton X4110G

---

drivers/platform/x86/acer-wireless.c

Sending the switch state change twice within the same frame is invalid
evdev protocol and only works if the client handles keys immediately as
well. Processing events immediately is incorrect, it forces a fake
order of events that does not exist on the device.
Recent versions of libinput changed to only process the device state and
SYN_REPORT time, so now the key event is lost.
Same fix as bff5bf9db1c94 "platform/x86: asus-wireless: send an
EV_SYN/SYN_REPORT between state changes"
https://phabricator.endlessm.com/T20508
Signed-off-by: Daniel Drake <drake@endlessm.com>

acer-wireless: send an EV_SYN/SYN_REPORT between state changes

---

drivers/platform/x86/ideapad-laptop.c

This reverts commit 7a2cc124474eafd78b7cf785d0d4d76b69e47fbc.
Userspace is now treating KEY_WLAN as airplane-mode, so we can drop this
change.
https://phabricator.endlessm.com/T20508

Revert "ideapad_laptop: Makes radio ON/OFF key emit KEY_RFKILL"

---

drivers/bluetooth/btusb.c

https://phabricator.endlessm.com/T19633

Add 04ca:3015 to the QCA Rome family and switch from BTUSB_RESET_RESUME to USB_QUIRK_RESET_RESUME

---

drivers/bluetooth/btusb.c

https://phabricator.endlessm.com/T19633

[eos3.3] Add 04ca:3015 to the QCA Rome family and switch from BTUSB_RESET_RESUME to USB_QUIRK_RESET_RESUME

---

drivers/net/ethernet/realtek/r8169.c

Driver check the wrong register bit in rtl_ocp_tx_cond() that keep driver
waiting until timeout.
Fix this by waiting for the right register bit.
Signed-off-by: Chunhao Lin <hau@realtek.com>
Signed-off-by: David S. Miller <davem@davemloft.net>

r8169: fix RTL8168EP take too long to complete driver initialization.

---

drivers/bluetooth/btusb.c

This reverts commit a0085f2510e8976614ad8f766b209448b385492f.
This may cause spurious wake-ups or prevent the system from entering
suspend at all.
https://patchwork.kernel.org/patch/10121401/
https://phabricator.endlessm.com/T20764

Revert "Bluetooth: btusb: driver to enable the usb-wakeup feature"

---

sound/soc/codecs/rt5645.c

https://phabricator.endlessm.com/T21052

ASoC: rt5645: Introduce mapping for ACPI-defined GPIO

---

drivers/gpu/drm/nouveau/nouveau_drm.c

ASUS ZenBook UX550GEX has dual GPU (Intel CoffeeLake+NVIDIA GP107),
the nouveau will hit kernel panic during shutdown and fail to suspend.
Disable it for now, and revisit later for a proper fix.
https://phabricator.endlessm.com/T21111

Disable nouveau on ASUS ZenBook Pro 15 UX550GEX

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The NV GTX 1050M of FX570UD cannot resume back from suspend with the
normal display when use the nouveau without setting the module parameter
noaccel.
Set the nouveau's module parameter noaccel to 1 can fix this problem.
https://phabricator.endlessm.com/T21413

nouveau_drm: ASUS FX570UD can't resume with nouveau

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The Acer Nitro N50-600 has Nvidia GTX 1060 and will occasionally fail
to resume from S3 suspend, with error messages:
nouveau 0000:01:00.0: timeout
nouveau 0000:01:00.0: secboot: error during falcon reset: -110
nouveau 0000:01:00.0: gr: init failed, -110
nouveau 0000:01:00.0: init failed with -110
Disable runtime power management and acceleration in order to avoid
this. Since the chipset number (0x136) does not match the existing
blacklists, create new blacklists which we can use for general
DMI vendor/product name matches and move one existing entry there.
https://phabricator.endlessm.com/T21513

nouveau: disable runtime pm and acceleration on Acer Nitro N50-600

---

sound/pci/hda/patch_realtek.c

This ASUS D640SA desktop whose mother board is D640MB has
- two jacks which are a headphone and a mic on the front panel,
- three jacks which are a mic, a line out and a line in on the rear
panel
- one internal speaker.
If I plug a headphone to the front headphone jack, there will be sound
through the headphone jack, and no sound through the internal speaker.
If I unplug the headphone from the the headphone jack, there will be
sound through the internal speaker.  And always no sound through rear
line out, when I plug a headphone or an externel speaker to the rear
line out jack.
Besides, I had checked and toggled the Auto-Mute Mode in alsamixer, but
the rear line out still was not working.  Then I checked the sound
settings in GUI, and found there was no "Line Out" could be chosen, only …

ALSA: hda/realtek: Enable audio line out on ASUS D640SA

---

drivers/bluetooth/btusb.c

Without this patch we can't establish a SCO connection with this
adapter.
This adapter is named "IMC Networks" under lsusb.
T:  Bus=01 Lev=01 Prnt=01 Port=07 Cnt=02 Dev#=  3 Spd=12   MxCh= 0
P:  Vendor=13d3 ProdID=3496 Rev= 0.01
C:* #Ifs= 2 Cfg#= 1 Atr=e0 MxPwr=100mA
E:  Ad=83(I) Atr=01(Isoc) MxPS=   0 Ivl=1ms
E:  Ad=03(O) Atr=01(Isoc) MxPS=   0 Ivl=1ms
I:  If#= 1 Alt= 1 #EPs= 2 Cls=e0(wlcon) Sub=01 Prot=01 Driver=btusb
E:  Ad=83(I) Atr=01(Isoc) MxPS=   9 Ivl=1ms
E: …

Bluetooth: Add a new 13d3:3496 QCA_ROME device

---

drivers/bluetooth/btrtl.c
drivers/bluetooth/btusb.c

Without these patches we cannot turn on the Bluethooth adapter on ASUS E406MA.
T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=12   MxCh= 0
P:  Vendor=2ff8 ProdID=b011 Rev= 2.00
S:  Manufacturer=Realtek
S:  Product=802.11n WLAN Adapter
S:  SerialNumber=00e04c000001
C:* #Ifs= 2 Cfg#= 1 Atr=e0 MxPwr=500mA
E:  Ad=03(O) Atr=01(Isoc) MxPS=   0 Ivl=1ms
E:  Ad=83(I) Atr=01(Isoc) MxPS=   0 Ivl=1ms
I:  If#= 1 Alt= 1 #EPs= 2 Cls=e0(wlcon) Sub=01 Prot=01 Driver=btusb
E: …

Bluetooth: Add a new Realtek 8723DE ID 2ff8:b011

---

drivers/mfd/intel-lpss-pci.c

This reverts commit 76a2a17.
Upstream has new patch for this issue
https://patchwork.ozlabs.org/patch/916118/
https://phabricator.endlessm.com/T22486

Revert "mfd: intel-lpss: Add new quirk for ELAN touchpad on Coffee Lake"

---

drivers/bluetooth/btusb.c

Without this patch we cannot turn on the Bluethooth adapter on HP
14-bs007la.
T:  Bus=01 Lev=02 Prnt=03 Port=00 Cnt=01 Dev#=  4 Spd=12   MxCh= 0
P:  Vendor=0bda ProdID=b009 Rev= 2.00
S:  Manufacturer=Realtek
S:  Product=802.11n WLAN Adapter
S:  SerialNumber=00e04c000001
C:* #Ifs= 2 Cfg#= 1 Atr=e0 MxPwr=500mA
E:  Ad=03(O) Atr=01(Isoc) MxPS=   0 Ivl=1ms
E:  Ad=83(I) Atr=01(Isoc) MxPS=   0 Ivl=1ms
I:  If#= 1 Alt= 1 #EPs= 2 Cls=e0(wlcon) Sub=01 Prot=01 Driver=btusb
E: …

Bluetooth: Add a new Realtek 8723DE ID 0bda:b009

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The NV GTX 1050M of X560UD cannot resume back from suspend with the
normal display when use the nouveau without setting the module parameter
noaccel.
Set the nouveau's module parameter noaccel to 1 can fix this problem.
https://phabricator.endlessm.com/T22813

nouveau_drm: ASUS X560UD can't resume with nouveau

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The NV GTX 1050 Ti of Predator Orion 5-100 cannot resume back from
suspend with the normal display when use the nouveau without setting the
module parameters runpm and noaccel.
Set the nouveau's module parameters runpm to 0 and noaccel to 1 can fix
this problem.
https://phabricator.endlessm.com/T21605

nouveau_drm: Acer Predator Orion 5-100 can't resume with nouveau

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The NV GTX 1050M of X705FD and MX150 on X530UN cannot resume back
from suspend with the normal display.
Setting the module parameters noaccel=1 and runpm=0 fix it.
https://phabricator.endlessm.com/T22813
https://phabricator.endlessm.com/T23033

nouveau_drm: disable runpm and accel on ASUS X530UN and X705FD

---

drivers/staging/rtlwifi/rtl8822be/sw.c

The laptop ASUS X530UN's rtl8822be cannnot find any WiFi access point
with enabled ASPM.
[    8.591333] r8822be: module is from the staging directory, the
quality is unknown, you have been warned.
[    8.593122] r8822be 0000:02:00.0: enabling device (0000 -> 0003)
[    8.669163] r8822be: Using firmware rtlwifi/rtl8822befw.bin
[    9.289939] r8822be: rtlwifi: wireless switch is on
[   10.056426] r8822be 0000:02:00.0 wlp2s0: renamed from wlan0
...
[   11.952534] r8822be: halmac_init_hal failed
[   11.955933] r8822be: halmac_init_hal failed
[   11.956227] r8822be: halmac_init_hal failed
[   22.007942] r8822be: halmac_init_hal failed
Disabling ASPM for rtl8822be on ASUS X530UN can fix this bug.
https://phabricator.endlessm.com/T23038

r8822be: Disable ASPM of r8822be on ASUS X530UN

---

sound/pci/hda/patch_realtek.c

The Acer desktop X2660G with ALC662 can't detect the headset microphone
until ALC662_FIXUP_ACER_X2660G_HEADSET_MODE quirk applied.
https://phabricator.endlessm.com/T23133

ALSA: hda/realtek - Enable headset mic of Acer X2660G with ALC662

---

debian.master/control.d/flavour-control.stub
debian.master/control.stub.in
debian/rules.d/2-binary-arch.mk

Import meta packages from linux-meta that map to the versioned packages
built by the linux source package. This way we can get rid of linux-meta
and don't need to bump its ABI version on every rebase.
https://phabricator.endlessm.com/T16504

Import linux-meta packages

---

sound/pci/hda/patch_realtek.c

The Acer desktop vCopperbox with ALC269VC cannot detect the MIC of
headset, the line out and internal speaker until
ALC269VC_FIXUP_ACER_VCOPPERBOX_PINS quirk applied.
https://phabricator.endlessm.com/T21388

ALSA: hda/realtek - Enable audio jacks of Acer vCopperbox with ALC269VC

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The NV GTX 1050Ti of Acer Nitro N50-100 cannot resume back from suspend
with the normal display.
Setting the module parameters noaccel=1 and runpm=0 fix it.
https://phabricator.endlessm.com/T23367

nouveau_drm: Disable runpm and accel on Acer Nitro N50-100

---

drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c

[Why]
If there is no program explicitly setting the backlight
brightness (for example, during a minimal install of linux), the
hardware defaults to maximum brightness but the backlight_device
defaults to 0 value.  Thus, settings displays the wrong brightness
value.
[How]
When creating the backlight device, set brightness to max
https://phabricator.endlessm.com/T21064
Signed-off-by: David Francis <David.Francis@amd.com>

drm/amdgpu: Read back max backlight value at boot

---

drivers/gpu/drm/i915/i915_irq.c
drivers/gpu/drm/i915/intel_crt.c
drivers/gpu/drm/i915/intel_display.c
drivers/gpu/drm/i915/intel_dp.c
drivers/gpu/drm/i915/intel_dp_mst.c
drivers/gpu/drm/i915/intel_dsi.c
drivers/gpu/drm/i915/intel_dvo.c
drivers/gpu/drm/i915/intel_hdmi.c
drivers/gpu/drm/i915/intel_lvds.c
drivers/gpu/drm/i915/intel_sdvo.c
drivers/gpu/drm/i915/intel_tv.c

These two upstream commits:
1. drm/i915: Fix PIPESTAT irq ack on i965/g4x ea6ac2b5cf18c50321208952f3ff91810174926d
2. drm/i915: Allow DBLSCAN user modes with eDP/LVDS/DSI d85341e000f14c18abec5d97a008432d4cd30426
fix "Asus X441UAR SKU2: Internal screen not display after switch to Mirror mode" issue.
https://phabricator.endlessm.com/T23517

drm/i915: Fix PIPESTAT irq ack on i965/g4x

---

drivers/platform/x86/asus-wmi.c

The asus_wmi will send the keyboard backlight brightness change
notification during booting, resuming and pressing function key.  The
notification pops up the keyboard backlight OSD on the screen.  However,
poping up OSD during booting and resuming is not necessary and confuses
users.
This patch adds the keyboard brightness change reasons and makes sure
only send keyboard backlight brightness change nitification by pressing
the function key.
https://phabricator.endlessm.com/T23126

asus-wmi: Disable kbd_led change notification for booting and resuming

---

drivers/usb/core/quirks.c

After going into S3/s2idle suspend, sometimes there will be a GPE
event from Embedded Controller which indicates a wake up signal from
the USB controller. Then the system will wake up unexpectedly. After
removing the btusb driver or just turn off bluetooth, it goses to
suspend just fine. However, there's neither paired nor connected
devices which could possibly wake up the system when it reproduces.
Quirks like USB_QUIRK_RESET_RESUME, USB_QUIRK_RESET, USB_QUIRK_NO_LPM,
USB_QUIRK_IGNORE_REMOTE_WAKEUP do no help.
Apply USB_QUIRK_DISCONNECT_SUSPEND to avoid the issue until the root
cause found and addressed.
https://phabricator.endlessm.com/T23395

USB: Force disconnect Intel bluetooth adapter during suspend

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The NV GTX 1050M of ASUS UX533FD cannot resume back from suspend with
the normal display.
Using nouveau with parameter noaccel=1 fixes it.
https://phabricator.endlessm.com/T23227
https://phabricator.endlessm.com/T23291

nouveau_drm: Disable accel on ASUS UX533FD

---

drivers/gpu/drm/nouveau/nouveau_drm.c

The NV GTX 1050M of ASUS X570ZD cannot resume back from suspend with
the normal display.
Using nouveau with parameter noaccel=1 fixes it.
https://phabricator.endlessm.com/T22624

nouveau_drm: Disable accel on ASUS X570ZD

---

drivers/gpu/drm/i915/i915_drv.h
drivers/gpu/drm/i915/intel_hotplug.c

I have few ASUS laptops, X705FD(Intel i7-8565), X560UD(Intel i5-8250U)
and X530UN(Intel i7-8550U) share the same problem. The HDMI connector
status stays 'connected' even the HDMI cable has been unplugged.
Then the status in sysfs would never change since then until we
do 'xrandr' to reprobe the devices. It would also cause the audio
output path cannot correctly swicth based on the connector status.
This commit kicks off a delayed work when the status remains unchanged
in the first hotplug event handling, which may not be the perfect
timing in some special cases.
https://phabricator.endlessm.com/T22838

drm/i915: re-check the hotplug with a delayed work

---

drivers/gpu/drm/radeon/radeon_drv.c

Radeon on the desktop like Acer Veriton Z4660G hits the errors during
booting which makes the Xorg cannot start.
[   31.576037] [drm:atom_op_jump [radeon]] *ERROR* atombios stuck in
loop for more than 5secs aborting
[   31.576058] [drm:atom_execute_table_locked [radeon]] *ERROR* atombios
stuck executing 67C0 (len 254, WS 0, PS 4) @ 0x67CE
[   31.576064] [drm:atom_execute_table_locked [radeon]] *ERROR* atombios
stuck executing 612C (len 78, WS 12, PS 8) @ 0x6165
[   31.928696] radeon 0000:01:00.0: Wait for MC idle timedout !
[   32.099173] radeon 0000:01:00.0: Wait for MC idle timedout !
[   32.105505] radeon 0000:01:00.0: WB enabled
[   32.105506] radeon 0000:01:00.0: fence driver on ring 0 use gpu addr
0x0000000080000c00 and cpu addr 0x00000000789d04f1
[   32.105507] radeon 0000:01:00.0: …

radeon: Disable runtime pm on Acer Veriton Z4660G

---

drivers/platform/x86/asus-nb-wmi.c
drivers/platform/x86/asus-wmi.c

Handle the display toggle hotkey on Asus devices.
https://phabricator.endlessm.com/T20914

asus-nb-wmi: Handle the display toggle hotkey

---

drivers/gpu/drm/i915/intel_fbc.c

On many (all?) the Gemini Lake systems we work with, there is frequent
momentary graphical corruption at the top of the screen, and it
seems that disabling framebuffer compression can avoid this.
Disable fbc on GeminiLake until a solution is found.
https://bugs.freedesktop.org/show_bug.cgi?id=108085
https://phabricator.endlessm.com/T21409

i915: disable framebuffer compression on GeminiLake

---

drivers/gpu/drm/radeon/radeon_drv.c

Some Acer AIO desktops like Veriton Z4860G and Z6860G cannot boot into
desktop environment without disabling runtime PM of the AMD Radeon VGA
card R5-330.
https://phabricator.endlessm.com/T23948

radeon: Disable runtime pm on Acer Veriton Z4860G/Z6860G

---

include/linux/hid.h

The ASUS laptops start to support the airplane mode radio management
to replace the original mechanism of airplane mode toggle hotkey.
On the ASUS P5440FF, it presents as a HID device connecting via
I2C, named i2c-AMPD0001. When pressing it, the Embedded Controller
send hid report via I2C and switch the airplane mode indicator LED
based on the status.
However, it's not working because it fails to be identified as a
hidinput device. It fails in hidinput_connect() due to the macro
IS_INPUT_APPLICATION doesn't have HID_GD_WIRELESS_RADIO_CTLS as
a legit application code.
It's easy to add the HID I2C vendor and product id to the quirk
list and apply HID_QUIRK_HIDINPUT_FORCE to make it work. But it
makes more sense to support it as a generic input application.
Signed-off-by: Chris Chiu …

HID: input: support Microsoft wireless radio control hotkey

---

sound/pci/hda/patch_realtek.c

Apply more HDA verbs of ALC294 to enable the internal speaker of ASUS
UX333FA.
https://phabricator.endlessm.com/T24542

ALSA: hda/realtek: Enable internal speaker of ASUS UX333FA with ALC294

---

debian.master/config/annotations

Update the annotations to reflect what we have been shipping. When we
first enabled this flag it was not present in the config annotations.
https://phabricator.endlessm.com/T24265

fixup! config: Enable FRAMEBUFFER_CONSOLE_DEFERRED_TAKEOVER

---

sound/pci/hda/hda_generic.c

The internal microphone will not be listed on the report of "amixer -D
sysdefault" if the pin node of headset microphone has auto detection
feature.  When the headset is plugged and user chooses the internal
microphone as the input source, system only gets sound from headset's
microphone.
This patch makes internal microphone be listed whether the headset
microphone pin node is auto detection or not.
https://phabricator.endlessm.com/T24554

ALSA: hda: Fix the mic control when headset is plugged

---

sound/pci/hda/patch_realtek.c

The Acer Aspire C20-820 AIO's audio (1025:1065) with ALC269VC can't
detect the headset microphone until ALC269VC_FIXUP_ACER_HEADSET_MIC
quirk maps the NID 0x18 as the headset mic pin.
https://phabricator.endlessm.com/T24554

ALSA: hda/realtek: Enable headset mic of Acer C20-820 with ALC269VC

---

sound/pci/hda/patch_realtek.c

The headset mic of ASUS laptops like UX533FD, UX433FN and UX333FA, whose
CODEC is Realtek ALC294 has jack auto detection feature.  This patch
enable the feature.
https://phabricator.endlessm.com/T24542

ALSA: hda/realtek: Enable the headset mic auto detection for ASUS laptops

---

sound/pci/hda/patch_realtek.c

The headset pins of Acer TravelMate X514-51T of Crux_WL series do not
work correctly until ALC255_FIXUP_ACER_CRUX_MIC_NO_PRESENCE quirk is
applied.
https://phabricator.endlessm.com/T25184

ALSA: hda/realtek: Enable headset audio of Acer Crux_WL with ALC255

---

arch/x86/kernel/reboot.c

Laptops like Acer TravelMate X514-51T cannot reboot (hang in the BIOS
POST when reboot) until set it as efi reboot.
https://phabricator.endlessm.com/T25190

x86/reboot: Use efi reboot for Acer TravelMate X514-51T

---

drivers/pinctrl/intel/pinctrl-intel.c

The touchpad of the ASUS laptops E403NA, X540NA, X541NA are not
responsive after suspend/resume. The following error message
shows after resume.
i2c_hid i2c-ELAN1200:00: failed to reset device.
On these laptops, the touchpad interrupt is connected via a GPIO
pin which is controlled by Intel pinctrl. After system resumes,
the GPIO is in ACPI mode and no longer works as an IRQ.
Introduce a new quirk here by saving HOSTSW_OWN register during
suspend and restore at resume.
https://phabricator.endlessm.com/T14379

pinctrl:intel: New quirk to save HOSTSW_OWN for ASUS laptops

---

drivers/iommu/amd_iommu.c

On ASUS laptop X512DK with the realtek USB card reader, the NULL
pointer dereference happens while bringing up the rtsx_usb driver.
[    1.782281] BUG: unable to handle kernel NULL pointer dereference at 0000000000000090
[    1.782283] PGD 0 P4D 0
[    1.782285] Oops: 0000 [#1] SMP NOPTI
[    1.782287] CPU: 6 PID: 290 Comm: systemd-udevd Not tainted 4.20.0-2-generic #3+dev91.add2285bem1
[    1.782288] Hardware name: ASUSTeK COMPUTER INC. VivoBook_ASUSLaptop X512DK_X512DK/X512DK, BIOS X512DK.200 01/04/2019
[    1.782292] RIP: 0010:acpi_device_hid+0x6/0x30
[    1.782293] Code: ff ff 5b 31 c0 41 5c 5d c3 49 8b 84 24 20 02 00 00 48 85 c0 74 e4 48 8b 40 38 48 85 c0 75 d3 eb d9 90 90 90 0f 1f 44 00 00 55 <48> 8b 97 90 00 00 00 48 8d 8f 90 00 00 00 48 c7 c0 f7 4a ba b9 48
[    1.782294] RSP: …

iommu/amd: Fix a null pointer dereference for ACPI devices

---

drivers/iio/accel/st_accel_core.c
include/linux/iio/common/st_sensors.h

Platform-specific ST accelerometer mount matrix information can be
provided by returning a package of 6 integers from the ACPI _ONT
method. This has been seen on Acer products such as Veriton Z4860G,
Z6860G and A890, which include a ST SMO8840 sensor. We have also
confirmed experimentally that the Windows driver uses such information.
The _ONT data format was explained by a ST vendor contact. However,
strangely enough, the _ONT transformations must be applied after first
applying another mount matrix which we determined experimentally. ST
have not commented on why this is the case, but we imagine that perhaps
earlier devices (before _ONT was introduced) required this translation
and hence it became 'standard.'
Interpret the _ONT data and export the equivalent mount matrix to
userspace.
If …

iio: st_accel: use ACPI orientation data

---

sound/pci/hda/patch_realtek.c

The Acer TravelMate B114-21 laptop cannot detect and record sound from
headset MIC.  This patch adds the ALC233_FIXUP_ACER_HEADSET_MIC HDA verb
quirk chained with ALC233_FIXUP_ASUS_MIC_NO_PRESENCE pin quirk to fix
this issue.
https://phabricator.endlessm.com/T25933

ALSA: hda/realtek: Enable headset MIC of Acer TravelMate B114-21 with ALC233

---

arch/x86/kernel/reboot.c

This reverts commit 3ae73f12ed1800e7599e4eca1e82db25272cc3aa.
Upstream fixed this issue.
https://phabricator.endlessm.com/T25533

Revert "x86/reboot: Use efi reboot for Acer TravelMate X514-51T"

---

drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c

The Acer Aspire A315-21G cannot boot with the error:
Apr 09 11:28:59 endless kernel: AMD-Vi: Completion-Wait loop timed out
Apr 09 11:28:59 endless kernel: iommu ivhd0: AMD-Vi: Event logged [IOTLB_INV_TIMEOUT device=01:00.0 address=0x216d8e620]
This patch makes a workaround by adding a DMI quirk which disables
amdgpu's runtime pm for this model.
https://phabricator.endlessm.com/T26099

drm/amdgpu: Disable runtime pm for Acer Aspire A315-21G

---

drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c
drivers/pci/quirks.c

This reverts commit 9d19ad0.
Upstreams uses the the patch [1] to fix the issue for now.
https://phabricator.endlessm.com/T26211
[1]: https://patchwork.kernel.org/patch/10889269/

Revert "drm/amdgpu: Disable runtime pm for Acer Aspire A315-21G"

---

drivers/bluetooth/btusb.c

This reverts commit 644ee83acc02843cab015332863940ebb3fda1e4.
This USB id is now present upstream, so we are adding an extra entry to
the list to no effect.

Revert "Bluetooth: Add new Realtek 8822BE ID 13d3:3526"

---

sound/pci/hda/hda_codec.c

After suspending the device and bringing it back up the audio playback
does not work anymore. The device for sound output is listed as a
headphone device. Plugging in headphones no sound is audible neither.
This reverts commit 9c51afaceb61459d2becac8fb32c860bb084e643 to solve
this regression issue.
https://phabricator.endlessm.com/T26524

Revert "ALSA: hda - Enforces runtime_resume after S3 and S4 for each codec"

---

drivers/bluetooth/btusb.c

Without the QCA ROME setup routine these adapters fail to establish a SCO
connection.
T:  Bus=01 Lev=01 Prnt=01 Port=08 Cnt=01 Dev#=  2 Spd=12  MxCh= 0
P:  Vendor=13d3 ProdID=3491 Rev=00.01
C:  #Ifs= 2 Cfg#= 1 Atr=e0 MxPwr=100mA
I:  If#=0x0 Alt= 0 #EPs= 3 Cls=e0(wlcon) Sub=01 Prot=01 Driver=btusb
I:  If#=0x1 Alt= 0 #EPs= 2 Cls=e0(wlcon) Sub=01 Prot=01 Driver=btusb
T:  Bus=01 Lev=01 Prnt=01 Port=04 Cnt=01 Dev#=  2 Spd=12  MxCh= 0
P:  Vendor=13d3 ProdID=3501 Rev=00.01
C:  #Ifs= 2 Cfg#= 1 Atr=e0 MxPwr=100mA
I:  If#=0x0 Alt= 0 #EPs= 3 Cls=e0(wlcon) Sub=01 Prot=01 Driver=btusb
I:  If#=0x1 Alt= 0 #EPs= 2 Cls=e0(wlcon) Sub=01 Prot=01 Driver=btusb
Signed-off-by: João Paulo …

Bluetooth: Add two new QCA_ROME devices

---

net/rds/tcp.c

When it is to cleanup net namespace, rds_tcp_exit_net() will call
rds_tcp_kill_sock(), if t_sock is NULL, it will not call
rds_conn_destroy(), rds_conn_path_destroy() and rds_tcp_conn_free() to free
connection, and the worker cp_conn_w is not stopped, afterwards the net is freed in
net_drop_ns(); While cp_conn_w rds_connect_worker() will call rds_tcp_conn_path_connect()
and reference 'net' which has already been freed.
In rds_tcp_conn_path_connect(), rds_tcp_set_callbacks() will set t_sock = sock before
sock->ops->connect, but if connect() is failed, it will call
rds_tcp_restore_callbacks() and set t_sock = NULL, if connect is always
failed, rds_connect_worker() will try to reconnect all the time, so
rds_tcp_kill_sock() will never to cancel worker cp_conn_w and free the
connections. …

net: rds: force to destroy connection if t_sock is NULL in rds_tcp_kill_sock().

---

drivers/gpu/drm/i915/intel_ddi.c

The downgrade of the fullmodeset into fastset
intel_encoder->update_pipe, in possible scenario, skips the En/Dis-able
DDI. Hence breaks the HDCP state change handling.
We also don't have any hdcp tests in CI, because the shard runs don't
have hdcp capable outputs :-/
So this change fixs it by handling the HDCP state change request at
intel_encoder->update_pipe too along with enable and disable of the DDI.
Fixes: d19f958db23c ("drm/i915: Enable fastset for non-boot modesets.")
v2:
Added commit id that broke the HDCP [Daniel]
Signed-off-by: Ramalingam C <ramalingam.c@intel.com>
cc: Maarten Lankhorst <maarten.lankhorst@linux.intel.com>
cc: Hans de Goede <hdegoede@redhat.com>
cc: Daniel Vetter <daniel.vetter@intel.com>
Signed-off-by: Daniel Vetter <daniel.vetter@ffwll.ch>
Link: …

drm/i915: HDCP state handling in ddi_update_pipe

---

drivers/gpu/drm/i915/i915_drv.h
drivers/gpu/drm/i915/intel_audio.c
drivers/gpu/drm/i915/intel_cdclk.c
drivers/gpu/drm/i915/intel_display.c
drivers/gpu/drm/i915/intel_drv.h
sound/pci/hda/hda_codec.c

To fix
T26524 Hack device: after suspend the audio playback does not work anymore
T26862 Asus X512DK: HDMI audio disappear after resume from S3
T26929 E406MA: HDMI may have chance to fail sound playback after resume from suspend
We need commit 905801fe7237 drm/i915: Force 2*96 MHz cdclk on glk/cnl when audio power is enabled
We also need these commits to prevent screen to flicker when the CDCLK changes on
the laptop like ASUS E406MA after apply the commit "drm/i915: Force 2*96 MHz cdclk on glk/cnl when audio power is enabled". [1]
commit 48d9f87ddd21 drm/i915: Save the old CDCLK atomic state
commit 2b21dfbeee72 drm/i915: Remove redundant store of logical CDCLK state
commit 59f9e9cab3a1 drm/i915: Skip modeset for cdclk changes if possible
https://phabricator.endlessm.com/T26862 …

drm/i915: Force 2*96 MHz cdclk on glk/cnl when audio power is enabled

---

drivers/ata/ahci.c
drivers/pci/controller/Makefile
drivers/pci/controller/intel-nvme-remap.c

Consumer products that are configured by default to run the Intel SATA AHCI
controller in "RAID" or "Intel RST Premium With Intel Optane System
Acceleration" mode are becoming increasingly prevalent.
Unde this mode, NVMe devices are remapped into the SATA device and become
hidden from the PCI bus, which means that Linux users cannot access their
storage devices unless they go into the firmware setup menu to revert back
to AHCI mode - assuming such option is available. Lack of support for this
mode is also causing complications for vendors who distribute Linux.
Add support for the remapped NVMe mode by creating a virtual PCI bus,
where the AHCI and NVMe devices are presented separately, allowing the
ahci and nvme drivers to bind in the normal way.
Unfortunately the NVMe device …

PCI: Add Intel remapped NVMe device support

---

drivers/bluetooth/btrtl.c

Realtek RTL8822BE BT chip on ASUS X420FA cannot be turned on correctly
after on-off several times.  Bluetooth daemon sets BT mode failed when
this issue happens.
bluetoothd[1576]: Failed to set mode: Failed (0x03)
If BT is tunred off, then turned on again, it works correctly again.
This patch makes RTL8822BE BT reset on close to fix this issue.
https://phabricator.endlessm.com/T26102

Bluetooth: btrtl: HCI reset on close for RTL8822BE

---

drivers/net/wireless/rtl8723bu/os_dep/os_intfs.c

In eos3.5, CONFIG_ANDROID=n, so we were running this code, which
we've previously documented as being the essential thing to tell
cfg80211 that we've disconnected in the suspend/resume path.
In eos3.6, CONFIG_ANDROID=y so we were no longer doing this.
After suspend/resume, wifi reconnection is broken as a result.
"Fix" this by restoring the eos3.5 behaviour of running this codepath.
https://phabricator.endlessm.com/T20835
https://phabricator.endlessm.com/T27164

rtl8723bu: always indicate disconnect during netdev_close

---

security/Kconfig
security/Makefile
security/endlesspayg/Makefile
security/endlesspayg/endlesspayg.c

Allow the paygd PID to be set through
/sys/kernel/security/endlesspayg/paygd_pid
When set, paygd can no longer be ptraced.
https://phabricator.endlessm.com/T27045

Add Endless PAYG LSM

---

drivers/net/wireless/rtl8723bu/os_dep/ioctl_cfg80211.c

For some reason, the driver has logic to suppress raising disconnection
events when in these codepaths.
This causes mac80211 to believe the device is still connected. When the
user attempts to switch from one AP to another, the 2nd connection
will fail because of this confusion.
Follow the approach taken in newer Realtek drivers for other hardware,
where these events are only suppressed in the connection codepath,
and issued as normal during disconnection.
https://phabricator.endlessm.com/T27202

rtl8723bu: indicate disconnection events when disconnecting

---

debian.master/config/annotations

Turning on our LSM broke the build because the packaging strictly
enforces certain LSM options.  Add our LSM to those.
https://phabricator.endlessm.com/T27045

config: allow endlesspayg LSM to pass packaging checks

---

debian.master/control.stub.in
debian/rules.d/2-binary-arch.mk

This adds the initramfs for our PAYG images to the linux-image
package.
https://phabricator.endlessm.com/T27042

Endless packaging customization

---

drivers/gpu/drm/amd/amdgpu/gfx_v8_0.c

Without this pin, the csb buffer will be filled with inconsistent
data after S3 resume. And that will causes gfx hang on gfxoff
exit since this csb will be executed then.
https://phabricator.endlessm.com/T26295
Signed-off-by: Likun Gao <Likun.Gao@amd.com>
Tested-by: Paul Gover <pmw.gover@yahoo.co.uk>
Reviewed-by: Feifei Xu <Feifei.Xu@amd.com>
Reviewed-by: Xiaojie Yuan <xiaojie.yuan@amd.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>

drm/amdgpu: pin the csb buffer on hw init for gfx v8

---

drivers/nvme/host/core.c
drivers/nvme/host/nvme.h
drivers/nvme/host/pci.c

This issue can be fixed by these two commits:
* commit 1a87ee657c53 nvme: export get and set features
* commit d916b1be94b6 nvme-pci: use host managed power state for suspend
Commit d916b1be94b6 is modified for backporting.
https://phabricator.endlessm.com/T27483

Asus TP412FA: Intel 660P SSD suspend & resume issue, T27483

---

drivers/pinctrl/pinctrl-amd.c

When cold-booting Asus X434DA, GPIO 7 is found to be already configured
as an interrupt, and the GPIO level is found to be in a state that
causes the interrupt to fire.
As soon as pinctrl-amd probes, this interrupt fires and invokes
amd_gpio_irq_handler(). The IRQ is acked, but no GPIO-IRQ handler was
invoked, so the GPIO level being unchanged just causes another interrupt
to fire again immediately after.
This results in an interrupt storm causing this platform to hang
during boot, right after pinctrl-amd is probed.
Detect this situation and disable the GPIO interrupt when this happens.
This enables the affected platform to boot as normal. GPIO 7 actually is
the I2C touchpad interrupt line, and later on, i2c-multitouch loads and
re-enables this interrupt when it is ready to handle it. …

pinctrl/amd: disable spurious-firing GPIO IRQs

---

drivers/pinctrl/intel/pinctrl-intel.c

On Asus X571GT, GPIO 297 is configured as an interrupt and serves
for the touchpad. The touchpad will report input events much less
than expected after S3 suspend/resume, which results in extremely
slow cursor movement. However, the number of interrupts observed
from /proc/interrupts increases much more than expected even no
touching touchpad.
This is due to the value of PADCFG0 of PIN 225 for the interrupt
has been changed from 0x80800102 to 0x80100102. The GPIROUTIOXAPIC
is toggled on which results in the spurious interrupts. The PADCFG0
of PIN 225 is expected to be saved during suspend, but the 297 is
saved instead because the gpiochip_line_is_irq() expect the GPIO
offset but what's really passed to it is PIN number. In this case,
the /sys/kernel/debug/pinctrl/INT3450:00/gpio-ranges …

pinctrl: intel: remap the pin number to gpio offset for irq enabled pin

---

sound/pci/hda/patch_realtek.c

Original pin node values of ASUS UX431FL with ALC294:
0x12 0xb7a60140
0x13 0x40000000
0x14 0x90170110
0x15 0x411111f0
0x16 0x411111f0
0x17 0x90170111
0x18 0x411111f0
0x19 0x411111f0
0x1a 0x411111f0
0x1b 0x411111f0
0x1d 0x4066852d
0x1e 0x411111f0
0x1f 0x411111f0
0x21 0x04211020
1. Has duplicated internal speakers (0x14 & 0x17) which makes the output
route become confused. So, the output volume cannot be changed by
setting.
2. Misses the headset mic pin node.
This patch disables the confusing speaker (NID 0x14) and enables the
headset mic (NID 0x19).
https://phabricator.endlessm.com/T27316
Link: https://lore.kernel.org/r/20190902100054.6941-1-jian-hong@endlessm.com

ALSA: hda/realtek - Enable internal speaker & headset mic of ASUS UX431FL

---

drivers/bluetooth/btusb.c

The ASUS X412FA laptop contains a Realtek RTL8822CE device with an
associated BT chip using a USB ID of 04ca:4005. This ID is added to the
driver.
The /sys/kernel/debug/usb/devices portion for this device is:
T:  Bus=01 Lev=01 Prnt=01 Port=09 Cnt=04 Dev#=  4 Spd=12   MxCh= 0
D:  Ver= 1.00 Cls=e0(wlcon) Sub=01 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=04ca ProdID=4005 Rev= 0.00
S:  Manufacturer=Realtek
S:  Product=Bluetooth Radio
S:  SerialNumber=00e04c000001
C:* #Ifs= 2 Cfg#= 1 Atr=a0 MxPwr=500mA
E:  Ad=03(O) Atr=01(Isoc) MxPS= …

Bluetooth: btrtl: Additional Realtek 8822CE Bluetooth devices

---

drivers/mfd/intel-lpss-pci.c

It turned out Intel Gemini Lake doesn't use the same I2C timing
parameters as Broxton.
I got confirmation from the Windows team that Gemini Lake systems should
use updated timing parameters that differ from those used in Broxton
based systems.
Fixes: f80e78aa11ad ("mfd: intel-lpss: Add Intel Gemini Lake PCI IDs")
Tested-by: Chris Chiu <chiu@endlessm.com>
Signed-off-by: Jarkko Nikula <jarkko.nikula@linux.intel.com>

mfd: intel-lpss: Add default I2C device properties for Gemini Lake

---

drivers/hid/hid-asus.c
drivers/platform/x86/asus-wmi.c
drivers/platform/x86/wmi.c
include/linux/acpi.h
include/linux/platform_data/x86/asus-wmi.h

Improve DSTS WMI method ID detection which needs `wmi_get_acpi_device_uid` comes from the other commit.

asus-wmi: Improve DSTS WMI method ID detection

---

security/endlesspayg/endlesspayg.c

When we open("file", O_CREAT, ...) the create and open are caught by
different LSM hooks.  We need to catch the create instead of just
the open if we want to block creation.
https://phabricator.endlessm.com/T27046

endlesspayg: Hook inode create

---

drivers/watchdog/endlessdog.c

Increase the watchdog timeout. For the rationale see the ticket linked
below.
https://phabricator.endlessm.com/T27051

endlessdog: Increase timeout to 20 minutes

---

fs/proc/base.c
security/endlesspayg/endlesspayg.c
security/endlesspayg/endlesspayg.h

Stop the pid directory in proc from being populated for the holder
of the LSM
https://phabricator.endlessm.com/T27044

endlesspayg: Block proc populating for LSM user

---

sound/soc/intel/boards/bytcr_rt5640.c

Add quirks to select the correct input map, jack-detect options
and channel map to enable jack sensing and headset microphone.
This device uses IN1 for its internal MIC and JD2 for jack-detect.

ASoC: Intel: bytcr_rt5640: Add quirks for ARCHOS Cesium 140

---

drivers/acpi/sleep.c

The role of the s2idle_wakeup variable is to cause
acpi_pm_wakeup_event() and acpi_pm_notify_handler() to
increment pm_abort_suspend and trigger a wakeup from
suspend-to-idle in case the ACPI SCI wakeup was canceled
by acpi_s2idle_wake().
However, for this purpose it need not be set in acpi_s2idle_wake()
and cleared in acpi_s2idle_sync(), respectively.  In fact, it
may be set as early as in acpi_s2idle_prepare() and cleared as
late as in acpi_s2idle_restore(), so do that to allow subsequent
changes to be simpler.
This change is not expected to alter functionality.
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
Acked-by: Thomas Gleixner <tglx@linutronix.de>

ACPI: PM: Set s2idle_wakeup earlier and clear it later

---

security/endlesspayg/endlesspayg.c

Some incredibly misguided EFI implementations have a vendor specific
SecureBootOption EFI variable that allows disabling secure boot
from userspace even when not in setup mode.
Block access to that for payg systems.
https://phabricator.endlessm.com/T27913

endlesspayg: Protect SecureBootOption EFI variable

---

drivers/pci/msi.c

MSI-X vector control's bit 0 is the mask bit, which masks the
corresponding interrupt request, or not. Other reserved bits might be
used for other purpose by device vendors. For example, the values of
Kingston NVMe SSD's MSI-X vector control are neither 0, nor 1, but other
values [1].
The original restoring logic in system resuming uses the whole MSI-X
vector control value as the flag to set/clear the mask bit. However,
this logic conflicts the idea mentioned above. It may mislead system to
disable the MSI-X vector entries. That makes system get no interrupt
from Kingston NVMe SSD after resume and usually get NVMe I/O timeout
error.
[  174.715534] nvme nvme0: I/O 978 QID 3 timeout, completion polled
This patch takes only the mask bit of original MSI-X vector control
value as the flag to …

PCI/MSI: Fix restoring of MSI-X vector control's mask bit

---

drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu.h
drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_8723b.c
drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_core.c

The RTL8723BU has problems connecting to AP after each warm reboot.
Sometimes it returns no scan result, and in most cases, it fails
the authentication for unknown reason. However, it works totally
fine after cold reboot.
Compare the value of register SYS_CR and SYS_CLK_MAC_CLK_ENABLE
for cold reboot and warm reboot, the registers imply that the MAC
is already powered and thus some procedures are skipped during
driver initialization. Double checked the vendor driver, it reads
the SYS_CR and SYS_CLK_MAC_CLK_ENABLE also but doesn't skip any
during initialization based on them. This commit only tells the
RTL8723BU to do full initilization without checking MAC status.
https://phabricator.endlessm.com/T28000

rtl8xxxu: fix RTL8723BU connection failure issue after warm reboot

---

drivers/gpu/drm/i915/display/intel_bios.c

The first come first served apporoach to handling the VBT
child device AUX ch conflicts has backfired. We have machines
in the wild where the VBT specifies both port A eDP and
port E DP (in that order) with port E being the real one.
So let's try to flip the preference around and let the last
child device win once again.
Cc: Jani Nikula <jani.nikula@intel.com>
Tested-by: Masami Ichikawa <masami256@gmail.com>
Tested-by: Torsten <freedesktop201910@liggy.de>
Bugzilla: https://bugs.freedesktop.org/show_bug.cgi?id=111966
Fixes: 36a0f92020dc ("drm/i915/bios: make child device order the priority order")
Signed-off-by: Ville Syrjälä <ville.syrjala@linux.intel.com>
Link: https://patchwork.freedesktop.org/patch/msgid/20191011202030.8829-1-ville.syrjala@linux.intel.com …

drm/i915: Favor last VBT child device with conflicting AUX ch/DDC pin

---

sound/pci/hda/patch_realtek.c

Laptops like ASUS UX431FLC and UX431FL can share the same audio quirks.
But UX431FLC needs one more step to enable the internal speaker: Pull
the GPIO from CODEC to initialize the AMP.
https://phabricator.endlessm.com/T28694
Fixes: 60083f9e94b2 ("ALSA: hda/realtek - Enable internal speaker & headset mic of ASUS UX431FL")
Link: https://lore.kernel.org/r/20191125093405.5702-1-jian-hong@endlessm.com

ALSA: hda/realtek - Enable internal speaker of ASUS UX431FLC

---

drivers/ata/ahci.c

Intel Comet Lake should use the default LPM policy for mobile chipsets.
So, add the PCI ID to the driver list of supported devices.

ahci: Add Intel Comet Lake PCH RAID PCI ID

---

sound/pci/hda/patch_realtek.c

ASUS reported that there's an additional speaker which serves as
the subwoofer and uses DAC 0x02. It dose not work with the commit
73a723348a43 ("ALSA: hda/realtek - Enable internal speaker of ASUS
UX431FLC") which enables the amplifier and front speakers. This
commit enables the subwoofer to improve the acoustic experience.
https://phabricator.endlessm.com/T28694

ALSA: hda/realtek - Enable the subwoofer of ASUS UX431FLC

---

drivers/platform/x86/asus-wmi.c

Some of ASUS laptops like UX431FL keyboard backlight cannot be set to
brightness 0. According to ASUS' information, the brightness should be
0x80 ~ 0x83. This patch fixes it by following the logic.
https://phabricator.endlessm.com/T28949
Fixes: e9809c0b9670 ("asus-wmi: add keyboard backlight support")

platform/x86: asus-wmi: Fix keyboard brightness cannot be set to 0

---

drivers/net/wireless/intel/iwlwifi/mvm/scan.c

The Intel(R) Dual Band Wireless AC 9461 WiFi keeps restarting until
commit 06eb547c4ae4 ("iwlwifi: mvm: fix scan config command size") is
reverted.
https://phabricator.endlessm.com/T28926

Revert "iwlwifi: mvm: fix scan config command size"

---

drivers/pci/quirks.c

https://phabricator.endlessm.com/T27618

PCI: Increase D3 delay for AMD Ryzen5/7 XHCI controllers

---

sound/pci/hda/patch_realtek.c

A headset on the laptop like ASUS B9450FA does not work, until quirk
ALC294_FIXUP_ASUS_HPE is applied.
https://phabricator.endlessm.com/T29120

ALSA: hda/realtek - Enable the headset of ASUS B9450FA with ALC294

---

drivers/mfd/intel-lpss-pci.c

[ Upstream commit dd047dce3a6f5233b98e792e2287cc549da35879 ]
Intel Comet Lake PCH-H has the same LPSS than Intel Cannon Lake.
Add the new IDs to the list of supported devices.
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Signed-off-by: Lee Jones <lee.jones@linaro.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

mfd: intel-lpss: Add Intel Comet Lake PCH-H PCI IDs

---

sound/pci/hda/patch_realtek.c

A headset on the desktop like Acer N50-600 does not work, until quirk
ALC662_FIXUP_ACER_NITRO_HEADSET_MODE is applied.
https://phabricator.endlessm.com/T27589

LSA: hda/realtek - Enable the headset of Acer N50-600 with ALC662

---

drivers/i2c/busses/i2c-nvidia-gpu.c

Nvidia card may come with a "phantom" UCSI device, and its driver gets
stuck in probe routine, prevents any system PM operations like suspend.
There's an unaccounted case that the target time can equal to jiffies in
gpu_i2c_check_status(), let's solve that by using readl_poll_timeout()
instead of jiffies comparison functions.
https://phabricator.endlessm.com/T29189
Fixes: c71bcdcb42a7 ("i2c: add i2c bus driver for NVIDIA GPU")
Suggested-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Signed-off-by: Kai-Heng Feng <kai.heng.feng@canonical.com>
Reviewed-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Reviewed-by: Ajay Gupta <ajayg@nvidia.com>
Tested-by: Ajay Gupta <ajayg@nvidia.com>
Signed-off-by: Wolfram Sang <wsa@the-dreams.de>

i2c: nvidia-gpu: Handle timeout correctly in gpu_i2c_check_status()

---

net/mac80211/tx.c

The original patch didn't copy the ieee80211_is_data() condition
because on most drivers the management frames don't go through
this path. However, they do on iwlwifi/mvm, so we do need to keep
the condition here.
Fixes: ce2e1ca70307 ("mac80211: Check port authorization in the ieee80211_tx_dequeue() case")
Signed-off-by: Johannes Berg <johannes.berg@intel.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
https://phabricator.endlessm.com/T29854

mac80211: fix authentication with iwlwifi/mvm

---

drivers/pci/quirks.c

Qualcomm Atheros Killer E2500 ethernet on Intel coffee lake chipset
0xa334 causes huge amount of PCIe AER error spam
pcieport 0000:00:1d.0: AER: Corrected error received: 0000:07:00.0
alx 0000:07:00.0: AER: PCIe Bus Error: severity=Corrected, type=Data Link Layer, (Receiver ID)
alx 0000:07:00.0: AER:   device [1969:e0b1] error status/mask=00000040/00002000
alx 0000:07:00.0: AER:    [ 6] BadTLP
This workaround is intentionally restricted to CFL 0xa334 where the
Qualcomm Atheros Killer E2500 ethernet presents behind the quirked PCI
bridge, in order to avoid side effects on other systems
https://phabricator.endlessm.com/T29786

PCI: Disable AER for CFL 0xa334 with Atheros Killer E2500 ethernet

---

drivers/acpi/sleep.c

This reverts commit a2ad686c07d3d53558aae56a80a4a929b7e75e03.
The ECS EF20EA hangs during resume from s2idle by a keystroke
problem will be gone after this. Revert it until a better solution
from upstream.
https://phabricator.endlessm.com/T29893

Revert "ACPI: PM: s2idle: Prevent spurious SCIs from waking up the system"

---

drivers/platform/x86/asus-wmi.c

On the ASUS laptop UX325JA/UX425JA, most of the media keys are not
working due to the ASUS WMI driver fails to be loaded. The error
messages as follows lead to the failure of asus_wmi_evaluate_method.
ACPI BIOS Error (bug): AE_AML_BUFFER_LIMIT, Field [IIA3] at bit offset/length 96/32 exceeds size of target Buffer (96 bits) (20200326/dsopcode-203)
No Local Variables are initialized for Method [WMNB]
ACPI Error: Aborting method \_SB.ATKD.WMNB due to previous error (AE_AML_BUFFER_LIMIT) (20200326/psparse-531)
The DSDT for the WMNB part shows that 5 DWORD required for local
variables and the 3rd variable IIA3 hit the buffer limit.
Method (WMNB, 3, Serialized)
{ ..
CreateDWordField (Arg2, Zero, IIA0)
CreateDWordField (Arg2, 0x04, IIA1)
CreateDWordField (Arg2, 0x08, IIA2)
CreateDWordField …

platform/x86: asus_wmi: Reserve more space for struct bias_args

---

sound/usb/mixer.c

The Asus USB DAC is a USB type-C audio dongle for connecting to
the headset and headphone. The volume minimum value -23040 which
is 0xa600 in hexdecimal with the resolution value 1 indicates
this should be endianess issue caused by the firmware bug. Add
a volume quirk to fix the volume control problem.
Also fixes this warning:
Warning! Unlikely big volume range (=23040), cval->res is probably wrong.
[5] FU [Headset Capture Volume] ch = 1, val = -23040/0/1
Warning! Unlikely big volume range (=23040), cval->res is probably wrong.
[7] FU [Headset Playback Volume] ch = 1, val = -23040/0/1

ALSA: usb: mixer: volume quirk for ESS Technology Asus USB DAC

---

security/endlesspayg/endlesspayg.c

After a PAYG computer is permanently unlocked, the EOSPAYG_active EFI
variable is deleted. With that variable gone, on the next boot eos-paygd
will no longer activate the LSM, so it makes sense for the LSM to
deactivate itself; otherwise some other process could theoretically
activate it. See the ticket for more discussion.
https://phabricator.endlessm.com/T30284

endlesspayg: Deactivate LSM after permanent unlock

---

sound/pci/hda/patch_realtek.c

The Acer Veriton N4660G desktop's audio (1025:1248) with ALC269VC cannot
detect the headset microphone until ALC269VC_FIXUP_ACER_MIC_NO_PRESENCE
quirk maps the NID 0x18 as the headset mic pin.
https://phabricator.endlessm.com/T30326
Link: https://lore.kernel.org/r/20200706071826.39726-3-jian-hong@endlessm.com

ALSA: hda/realtek: Enable headset mic of Acer Veriton N4660G with ALC269VC

---

sound/pci/hda/patch_realtek.c

The Acer TravelMate B311R-31 laptop's audio (1025:1430) with ALC256
cannot detect the headset microphone until
ALC256_FIXUP_ACER_MIC_NO_PRESENCE quirk maps the NID 0x19 as the headset
mic pin.
https://phabricator.endlessm.com/T30492
Link: https://lore.kernel.org/r/20200713060421.62435-1-jian-hong@endlessm.com

ALSA: hda/realtek: Enable headset mic of Acer TravelMate B311R-31 with ALC256

---

arch/arm64/boot/dts/rockchip/rk3399-pinebook-pro.dts

The cdn-dp sub driver probes the device failed on PINEBOOK Pro.
kernel: cdn-dp fec00000.dp: [drm:cdn_dp_probe [rockchipdrm]] *ERROR* missing extcon or phy
kernel: cdn-dp: probe of fec00000.dp failed with error -22
Then, the device halts all of the DRM related device jobs. For example,
the operations: vop_component_ops, vop_component_ops and
rockchip_dp_component_ops cannot be bound to corresponding devices. So,
Xorg cannot find the correct DRM device.
The USB type-C DisplayPort does not work for now. So, disable the
DisplayPort node until the type-C phy work has been done.
https://phabricator.endlessm.com/T30770
Link: https://patchwork.kernel.org/patch/11794141/#23639877

arm64: dts: rockchip: disable USB type-c DisplayPort

---

sound/pci/hda/patch_realtek.c

The ASUS D700SA desktop's audio (1043:2390) with ALC887 cannot detect
the headset microphone and another headphone jack until
ALC887_FIXUP_ASUS_HMIC and ALC887_FIXUP_ASUS_AUDIO quirks are applied.
The NID 0x15 maps as the headset microphone and NID 0x19 maps as another
headphone jack. Also need the function like alc887_fixup_asus_jack to
enable the audio jacks.
https://phabricator.endlessm.com/T30803
Signed-off-by: Kailang Yang <kailang@realtek.com>
Link: https://lore.kernel.org/r/20201007052224.22611-1-jhp@endlessos.org

ALSA: hda/realtek: Enable audio jacks of ASUS D700SA with ALC887

---

mm/shmem.c

We should be using fsparam_no_flag instead of fsparam_bool for this
attribute, otherwise mount expects a value to be passed to the option.
Also, fsparam_no_flag already covers both 'option' and 'nooption', and
we can differentiate them by the result from fs_parse.
This is modeled after fs/erofs/super.c.
https://phabricator.endlessm.com/T30464

fixup! tmpfs: add user_xattr mount option

---

drivers/pci/controller/vmd.c

Some platforms have an AHCI controller behind VMD. These platforms are
working correctly except for a case when the AHCI MSI is programmed with
VMD IRQ vector 0 (0xfee00000). When programmed with any other interrupt
(0xfeeNN000), the MSI is routed correctly and is handled by VMD. Placing
the AHCI MSI(s) in the fast-interrupt allow list solves the issue.
This also requires that VMD allocate more than one MSI/X vector and
changes the minimum MSI/X vectors allocated to two.
https://phabricator.endlessm.com/T30967
Signed-off-by: Jon Derrick <jonathan.derrick@intel.com>
Tested-by: Jian-Hong Pan <jhp@endlessos.org>

PCI: vmd: Add AHCI to fast interrupt list

---

include/net/bluetooth/hci_core.h

Starting with the upgrade to v5.8-rc3, I've noticed I wasn't able to
connect to my Bluetooth headset properly anymore. While connecting to
the device would eventually succeed, bluetoothd seemed to be confused
about the current connection state where the state was flapping hence
and forth. Bisecting this issue led to commit 3ca44c16b0dc (Bluetooth:
Consolidate encryption handling in hci_encrypt_cfm, 2020-05-19), which
refactored `hci_encrypt_cfm` to also handle updating the connection
state.
The commit in question changed the code to call `hci_connect_cfm` inside
`hci_encrypt_cfm` and to change the connection state. But with the
conversion, we now only update the connection state if a status was set
already. In fact, the reverse should be true: the status should be
updated if no status is …

Bluetooth: Fix update of connection state in `hci_encrypt_cfm`

---

sound/pci/hda/patch_realtek.c

ASUS TM420 had depop circuit for headphone.
It need to turn on by COEF bit.
[ fixed the missing enum definition by tiwai ]
https://phabricator.endlessm.com/T30825
Signed-off-by: Kailang Yang <kailang@realtek.com>
Link: https://lore.kernel.org/r/3d6177d7023b4783bf2793861c577ada@realtek.com

ALSA: hda/realtek - Enable headphone for ASUS TM420

---

drivers/gpu/drm/i915/i915_pci.c

We have an ASUS BR1100FKA equipped with Intel N6000 Jasper Lake. The DRM
is always probed failed due to the require_force_probe barrier placed by
Intel. Maybe, Intel has not enabled it well right now, so puts the
barrier here.
However, to make users enjoy Endless OS as much as possible, this patch
clears the require_force_probe flag for Jasper Lake's DRM.
This approach should be removed if Intel enables Jasper Lake chips well.
This will be different after kernel 5.11+ due to the commit 24ea098b7c0d
("drm/i915/jsl: Split EHL/JSL platform info and PCI ids").
https://phabricator.endlessm.com/T31213

[Endless] drm/i915: Clear require_force_probe for JSL DRM

---

Documentation/devicetree/bindings/arm/bcm/bcm2835.yaml
arch/arm/boot/dts/Makefile
arch/arm/boot/dts/bcm2711-rpi-4-b.dts
arch/arm/boot/dts/bcm2711-rpi-400.dts
arch/arm/boot/dts/bcm2711-rpi.dtsi
arch/arm/boot/dts/bcm2711.dtsi
arch/arm/boot/dts/bcm2835-rpi-a-plus.dts
arch/arm/boot/dts/bcm2835-rpi-a.dts
arch/arm/boot/dts/bcm2835-rpi-b-plus.dts
arch/arm/boot/dts/bcm2835-rpi-b-rev2.dts
arch/arm/boot/dts/bcm2835-rpi-b.dts
arch/arm/boot/dts/bcm2835-rpi-cm1.dtsi
arch/arm/boot/dts/bcm2835-rpi-zero-w.dts
arch/arm/boot/dts/bcm2835-rpi-zero.dts
arch/arm/boot/dts/bcm2835-rpi.dtsi
arch/arm/boot/dts/bcm2836-rpi-2-b.dts
arch/arm/boot/dts/bcm2837-rpi-3-a-plus.dts
arch/arm/boot/dts/bcm2837-rpi-3-b-plus.dts
arch/arm/boot/dts/bcm2837-rpi-3-b.dts
arch/arm/boot/dts/bcm2837-rpi-cm3.dtsi
arch/arm/boot/dts/bcm283x.dtsi
arch/arm64/boot/dts/broadcom/Makefile
arch/arm64/boot/dts/broadcom/bcm2711-rpi-400.dts

Applied related commits from upstream [1] to add RPi 400's device tree.
[1] https://git.kernel.org/pub/scm/linux/kernel/git/nsaenz/linux-rpi.git/log/?h=bcm2835-dt-next-2021-06-08-v2
https://phabricator.endlessm.com/T32106

arm: arm64: dts: Enable RPi 400 by adding its device tree

---

drivers/net/ethernet/broadcom/genet/bcmgenet.c

The Broadcom UniMAC MDIO bus from mdio-bcm-unimac module comes too late.
So, GENET cannot find the ethernet PHY on UniMAC MDIO bus. This leads
GENET fail to attach the PHY as following log:
bcmgenet fd580000.ethernet: GENET 5.0 EPHY: 0x0000
...
could not attach to PHY
bcmgenet fd580000.ethernet eth0: failed to connect to PHY
uart-pl011 fe201000.serial: no DMA platform data
libphy: bcmgenet MII bus: probed
...
unimac-mdio unimac-mdio.-19: Broadcom UniMAC MDIO bus
It is not just coming too late, there is also no way for the module
loader to figure out the dependency between GENET and its MDIO bus
driver unless we provide this MODULE_SOFTDEP hint.
This patch adds the soft dependency to load mdio-bcm-unimac module
before genet module to fix this issue.
https://phabricator.endlessm.com/T32142 …

net: bcmgenet: Add mdio-bcm-unimac soft dependency

---

fs/seq_file.c

There is no reasonable need for a buffer larger than this,
and it avoids int overflow pitfalls.
Suggested-by: Al Viro <viro@zeniv.linux.org.uk>
Signed-off-by: Eric Sandeen <sandeen@redhat.com>
CVE-2021-33909
Fixes: 058504edd026 ("fs/seq_file: fallback to vmalloc allocation")
Signed-off-by: Thadeu Lima de Souza Cascardo <cascardo@canonical.com>
Acked-by: Juerg Haefliger <juergh@canonical.com>
Acked-by: Benjamin M Romer <benjamin.romer@canonical.com>

UBUNTU: SAUCE: seq_file: Disallow extremely large seq buffer allocations

---

drivers/net/wireless/realtek/rtw88/rtw8821c.c

Enable RTL8821CE's type 4 chip.
https://phabricator.endlessm.com/T31296

rtw88: Enable RTL8821CE's type 4

---

drivers/net/wireless/realtek/rtw88/main.h
drivers/net/wireless/realtek/rtw88/pci.c
drivers/net/wireless/realtek/rtw88/pci.h
drivers/net/wireless/realtek/rtw88/rtw8821c.c

More and more laptops become frozen, due to the equipped RTL8821CE.
This patch follows the idea mentioned in commits 956c6d4f20c5 ("rtw88:
add quirks to disable pci capabilities") and 1d4dcaf3db9bd ("rtw88: add
quirk to disable pci caps on HP Pavilion 14-ce0xxx"), but disables its
PCI ASPM capability of RTL8821CE directly, instead of checking DMI.
Buglink:https://bugzilla.kernel.org/show_bug.cgi?id=215239
Fixes: 1d4dcaf3db9bd ("rtw88: add quirk to disable pci caps on HP Pavilion 14-ce0xxx")
https://phabricator.endlessm.com/T31296

[Endless] rtw88: 8821c: disable the ASPM of RTL8821CE

---

debian.master/control.stub.in

This reverts commit 974101219a701b2f0c56a5ebafc2088178d84e57.
Since libbpf 0.5.0-1~bpo11+1 and dwarves 1.22-4~bpo11+1 have built in
eos:master:core, they can provide the dependent packages for normal
linux 5.15 package now. So, drop the workaround.
https://phabricator.endlessm.com/T33162#929649

Revert "[DROP-ME] packaging: Downgrade dwarves dependent version to >= 1.20"

---

lib/iov_iter.c

The functions copy_page_to_iter_pipe() and push_pipe() can both
allocate a new pipe_buffer, but the "flags" member initializer is
missing.
Fixes: 241699cd72a8 ("new iov_iter flavour: pipe-backed")
To: Alexander Viro <viro@zeniv.linux.org.uk>
To: linux-fsdevel@vger.kernel.org
To: linux-kernel@vger.kernel.org
Signed-off-by: Max Kellermann <max.kellermann@ionos.com>
Signed-off-by: Al Viro <viro@zeniv.linux.org.uk>
https://phabricator.endlessm.com/T33272

lib/iov_iter: initialize "flags" in new pipe_buffer

---

drivers/gpu/drm/i915/display/intel_opregion.c

commit ea958422291de248b9e2eaaeea36004e84b64043 upstream.
The mapping from enum port to whatever port numbering scheme is used by
the SWSCI Display Power State Notification is odd, and the memory of it
has faded. In any case, the parameter only has space for ports numbered
[0..4], and UBSAN reports bit shift beyond it when the platform has port
F or more.
Since the SWSCI functionality is supposed to be obsolete for new
platforms (i.e. ones that might have port F or more), just bail out
early if the mapped and mangled port number is beyond what the Display
Power State Notification can support.
Fixes: 9c4b0a683193 ("drm/i915: add opregion function to notify bios of encoder enable/disable")
Cc: <stable@vger.kernel.org> # v3.13+
Cc: Ville Syrjälä <ville.syrjala@linux.intel.com>
Cc: Lucas De …

drm/i915/opregion: check port number bounds for SWSCI display power state

---

include/net/netfilter/nf_tables.h
include/net/netfilter/nf_tables_offload.h
net/netfilter/nf_tables_offload.c
net/netfilter/nft_dup_netdev.c
net/netfilter/nft_fwd_netdev.c
net/netfilter/nft_immediate.c

immediate verdict expression needs to allocate one slot in the flow offload
action array, however, immediate data expression does not need to do so.
fwd and dup expression need to allocate one slot, this is missing.
Add a new offload_action interface to report if this expression needs to
allocate one slot in the flow offload action array.
Fixes: be2861dc36d7 ("netfilter: nft_{fwd,dup}_netdev: add offload support")
Reported-and-tested-by: Nick Gregory <Nick.Gregory@Sophos.com>
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
https://phabricator.endlessm.com/T33282

netfilter: nf_tables_offload: incorrect flow offload action array size

---

drivers/gpu/drm/vc4/vc4_hdmi.c
drivers/gpu/drm/vc4/vc4_hdmi.h

commit 633be8c3c0c5e0cf176ce904083a4728ae8e4025 upstream.
Accessing the crtc->state pointer from outside the modesetting context
is not allowed. We thus need to copy whatever we need from the KMS state
to our structure in order to access it.
However, in the vc4 HDMI driver we do use that pointer in the ALSA code
path, and potentially in the hotplug interrupt handler path.
These paths both need access to the CRTC adjusted mode in order for the
proper dividers to be set for ALSA, and the scrambler state to be
reinstated properly for hotplug.
Let's copy this mode into our private encoder structure and reference it
from there when needed. Since that part is shared between KMS and other
paths, we need to protect it using our mutex.
https://phabricator.endlessm.com/T33279
Link: …

drm/vc4: hdmi: Prevent access to crtc->state outside of KMS

---

include/linux/security.h

The commit "UBUNTU: SAUCE: LSM: Create and manage the lsmblob data
structure." introduces the LSMBLOB_ENTRIES to maintain the slots of LSM
blob entries and makes sure it will not be out of boundary. Therefore,
the LSMBLOB_ENTRIES should be increased one more slot for endlesspayg.
However, EOS kernel builds endlesspayg into kernel image directly if
CONFIG_SECURITY is set. So, increase the slot of LSM by checking
CONFIG_SECURITY.
Fixes: "UBUNTU: SAUCE: LSM: Create and manage the lsmblob data structure."
https://phabricator.endlessm.com/T33261

[Endless] LSM: Increase LSM blob entries for endlesspayg

---

drivers/net/wireless/realtek/rtw88/main.c
drivers/net/wireless/realtek/rtw88/pci.c

Realtek RTL8821CE wireless keeps failed from time to time. All clues
point to power management things between rtw88 and the firmware. We do
not have a better solution currently. So, disable the lps_deep_mode and
ASPM for RTL8821CE as a workaround now.
https://phabricator.endlessm.com/T33794

[Endless] rtw88: Disable lps_deep_mode and ASPM for RTL8821CE

---

drivers/acpi/sleep.c

BugLink: https://bugs.launchpad.net/bugs/1981864
[ Upstream commit d52848620de00cde4a3a5df908e231b8c8868250 ]
ASUS B1400CEAE fails to resume from suspend to idle by default.  This was bisected back to commit df4f9bc4fb9c ("nvme-pci: add support for ACPI StorageD3Enable property") but this is a red herring to the problem.
Before this commit the system wasn't getting into deepest sleep state. Presumably this commit is allowing entry into deepest sleep state as advertised by firmware, but there are some other problems related to the wakeup.
As it is confirmed the system works properly with S3, set the default for this system to S3.
Reported-by: Jian-Hong Pan <jhp@endlessos.org>
Link: https://bugzilla.kernel.org/show_bug.cgi?id=215742
Signed-off-by: Mario Limonciello …

ACPI: PM: Block ASUS B1400CEAE from suspend to idle by default

---

debian.master/config/annotations
debian.master/control.stub.in
debian/rules.d/2-binary-arch.mk

Do not compress the kernel modules with ZSTD. Busybox cannot handle ZSTD
correctly now. Simply use uncompressed modules.
https://phabricator.endlessm.com/T34954

Do not compress the kernel modules with ZSTD

---

debian.master/config/annotations

The decompressed kernel image is too fat to fit in the memory boundary set by U-Boot on RPi. So, disable options: CONFIG_VIRTUALIZATION and CONFIG_XEN to shrink the kernel image size.
https://phabricator.endlessm.com/T34994

fixup! [Endless] config: arm64 build shrinking

---

drivers/pci/quirks.c

Realtek cards on Skylake/Kabylake systems cause a huge amount of PCIe AER error spam, so much that the mouse can't even be moved.
pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e5(Receiver ID)
pcieport 0000:00:1c.5:   device [8086:9d15] error status/mask=00000001/00002000
pcieport 0000:00:1c.5:    [ 0] Receiver Error
pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
pcieport 0000:00:1c.5: can't find device of ID00e5
pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
pcieport 0000:00:1c.5: can't find device of ID00e5
We think this is a pcieport bug - it can't find the device so it doesn't clear the error condition - but for now we just add a workaround.
This workaround is intentionally restricted to SKL/KBL systems where the …

PCI: Disable AER for Skylake/Kabylake systems with Realtek wifi

---

debian.master/config/annotations
include/linux/fortify-string.h

EOS has rebased on Debian bookworm having GCC 12.  So, revert some GCC downstream config modification.

Revert GCC downstream config modification

---

drivers/acpi/resource.c

The TongFang GMxXGxx/TUXEDO Stellaris/Pollaris Gen5 needs IRQ overriding
for the keyboard to work.
Adding an entry for this laptop to the override_table makes the internal
keyboard functional.
Signed-off-by: Werner Sembach <wse@tuxedocomputers.com>
Cc: All applicable <stable@vger.kernel.org>
Reviewed-by: Hans de Goede <hdegoede@redhat.com>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
Backport: f9b3ea02555e67e2e7bf95219953b88d122bd275

ACPI: resource: Do IRQ override on TongFang GMxXGxx

---

drivers/pci/controller/intel-nvme-remap.c

The Intel RST RAID enabled machines boot failed, because intel-nvme-remap module creates ROOT bus failed since commit ("PCI: Release resource invalidated by coalescing"). The commit tries to release invalidated resource.
The original intel-nvme-remap did not set the resources' parent memeber of the new remapped PCI bus within the new kernel (5.16+). So, it becomes the invalidated resource which is going to be released.
Besides, make the new generated remapped RAID controller skip the PM actions. Because, it is a virtual interface. The real RAID controller will handle the AHCI's PM actions through the intel-nvme-remap module.
https://phabricator.endlessm.com/T35112

fixup! PCI: Add Intel remapped NVMe device support

---

debian.master/config/annotations

We have ~36mb uncompressed kernel size limit on arm64 for the RPi4 u-boot setup. We edged over the limit with the new bookworm distro.
Disable FTRACE and DYNAMIC_DEBUG to save about 7.5mb.
https://phabricator.endlessm.com/T35122

[Endless] config: disable tracing and dynamic debug on arm64

---

include/linux/security.h
include/uapi/linux/lsm.h
security/endlesspayg/endlesspayg.c

Add Endless PAYG LSM ID to fix the warning oops message when initial PAYG LSM.
https://phabricator.endlessm.com/T35302

Fix PAYG LSM lsmid warning

---

sound/pci/hda/patch_realtek.c

JP-IK LEAP W502 laptop's headset mic is not enabled until ALC897_FIXUP_HEADSET_MIC_PIN3 quirk is applied.
Here is the original pin node values:
0x11 0x40000000
0x12 0xb7a60130
0x14 0x90170110
0x15 0x411111f0
0x16 0x411111f0
0x17 0x411111f0
0x18 0x411111f0
0x19 0x411111f0
0x1a 0x411111f0
0x1b 0x03211020
0x1c 0x411111f0
0x1d 0x4026892d
0x1e 0x411111f0
0x1f 0x411111f0
https://phabricator.endlessm.com/T35378

ALSA: hda/realtek: Enable headset mic of JP-IK LEAP W502 with ALC897
