endlessm/linux

drivers/gpu/drm/i915/intel_dp.c
This reverts commits 4e6e1a5 and 19cfb3f.
On the 3.16 kernel we need to revert both commits at the same time to
have the external display working and the backlight on at boot.
[endlessm/eos-shell#4981]
=> drm/i915: Fix backlight and external display issues on NL3/JWM laptops

drivers/gpu/drm/drm_crtc.c, drivers/gpu/drm/i915/intel_display.c
We'll do this in the X driver instead.
https://github.com/endlessm/eos-shell/issues/5693
=> Revert hiDPI hacks

drivers/acpi/button.c
=> ACPI / button: Use cached lid state when _LID is unreliable

drivers/acpi/property.c, drivers/base/core.c, drivers/base/platform.c, drivers/base/property.c, drivers/i2c/busses/i2c-designware-platdrv.c, drivers/mfd/intel-lpss-acpi.c, drivers/mfd/intel-lpss-pci.c, drivers/mfd/intel-lpss.c, drivers/mfd/intel-lpss.h, drivers/mfd/mfd-core.c, include/linux/mfd/core.h, include/linux/platform_device.h, include/linux/property.h
https://phabricator.endlessm.com/T11033
=> T11033: Fix Yoga 900 touchpad

drivers/platform/x86/asus-nb-wmi.c
https://phabricator.endlessm.com/T11110
=> T11110: Fix airplane-mode LED on the Asus N552VW, X456UA and X456UF

drivers/input/mouse/elan_i2c_core.c
Verified on X456UA and the TP work as expected.
=> Set ABS mode after Wake up touchpad per ELAN's suggestion.

drivers/pci/quirks.c
for https://phabricator.endlessm.com/T11715
=> Disable MSI on another problematic ASUS X456UR

drivers/gpu/drm/radeon/cik.c, drivers/gpu/drm/radeon/ni.c, drivers/gpu/drm/radeon/radeon_acpi.c, drivers/gpu/drm/radeon/si.c
Reduce severity of radeon error messages.
https://phabricator.endlessm.com/T11561
=> T11561: Reduce severity of radeon error messages

drivers/gpu/drm/radeon/cik.c, drivers/gpu/drm/radeon/ni.c, drivers/gpu/drm/radeon/radeon_acpi.c, drivers/gpu/drm/radeon/si.c, drivers/iommu/amd_iommu_init.c
Reduce severity of radeon and AMD IOMMU error messages.
https://phabricator.endlessm.com/T11561
=> T11561-eos2.6: Reduce severity of radeon error messages

drivers/idle/intel_idle.c
https://phabricator.endlessm.com/T6380
=> intel_idle: Force max_cstate to 1 on Asus Z550MA

arch/x86/include/asm/cpufeatures.h, arch/x86/include/asm/mwait.h, arch/x86/kernel/cpu/intel.c, arch/x86/kernel/process.c, drivers/acpi/acpica/dswload.c
https://phabricator.endlessm.com/T12887
=> Fix boot on Acer Aspire E14 ES1-432

arch/x86/Kconfig, arch/x86/include/asm/iosf_mbi.h, arch/x86/platform/atom/punit_atom_debug.c, arch/x86/platform/intel-quark/imr.c, drivers/acpi/acpi_lpss.c, drivers/dma/dw/platform.c, drivers/i2c/busses/i2c-designware-baytrail.c, drivers/powercap/intel_rapl.c, drivers/thermal/intel_quark_dts_thermal.c, drivers/thermal/intel_soc_dts_iosf.c
Without this patchset the Asus Z550SA would go through the shutdown process, but never actually power off. These 3 patches fix the problem.
https://phabricator.endlessm.com/T13012
=> T13012: Fix shutdown on Asus Z550SA

drivers/gpu/drm/i915/Makefile, drivers/gpu/drm/i915/hdmi_audio_if.c, drivers/gpu/drm/i915/hdmi_audio_if.h, drivers/gpu/drm/i915/i915_drv.h, drivers/gpu/drm/i915/i915_irq.c, drivers/gpu/drm/i915/i915_reg.h, drivers/gpu/drm/i915/i915_rpm.c, drivers/gpu/drm/i915/intel_display.c, drivers/gpu/drm/i915/intel_drv.h, drivers/gpu/drm/i915/intel_hdmi.c, drivers/gpu/drm/i915/intel_pm.c, sound/Kconfig, sound/Makefile, sound/hdmi_audio/Makefile, sound/hdmi_audio/intel_mid_hdmi_audio.c, sound/hdmi_audio/intel_mid_hdmi_audio.h, sound/hdmi_audio/intel_mid_hdmi_audio_if.c
https://phabricator.endlessm.com/T12916
=> sound: Enable LPE-HDMI

drivers/gpu/drm/i915/i915_drv.h, drivers/gpu/drm/i915/intel_display.c, drivers/gpu/drm/i915/intel_drv.h, drivers/gpu/drm/i915/intel_pm.c
This patch series solves an issue where hotplugging HDMI would give a corrupted display, and a system freeze on hot-unplug.
https://phabricator.endlessm.com/T13389
=> Fix Apollo Lake HDMI hotplug

ubuntu/i915/i915_drv.h, ubuntu/i915/intel_atomic.c, ubuntu/i915/intel_display.c, ubuntu/i915/intel_drv.h, ubuntu/i915/intel_pm.c
https://phabricator.endlessm.com/T13389
=> E402NA SKU2 HDMI fix

drivers/platform/x86/asus-wireless.c
https://phabricator.endlessm.com/T13914
=> asus-wireless: Use the correct HSWC parameter for each HID

drivers/acpi/button.c, sound/soc/codecs/rt5645.c
https://phabricator.endlessm.com/T6410
=> Add ECS EF20 internal microphone support

drivers/idle/intel_idle.c, drivers/mmc/host/sdhci-acpi.c
https://phabricator.endlessm.com/T14511
=> Fix freeze on Intel Baytrail machines with RTL8723BS

drivers/i2c/busses/i2c-designware-baytrail.c, drivers/i2c/busses/i2c-designware-core.c, drivers/i2c/busses/i2c-designware-core.h, drivers/i2c/busses/i2c-designware-pcidrv.c, drivers/i2c/busses/i2c-designware-platdrv.c
https://phabricator.endlessm.com/T6358
=> Fix cherrytrail i2c/PUNIT warnings

drivers/hid/hid-asus-rog.c
https://phabricator.endlessm.com/T15241
=> HID: asus-rog: add missing "if" to fix ASUS ZEN AIO keyboard support

drivers/platform/x86/acer-wmi.c
https://phabricator.endlessm.com/T15397
=> Pick upstream fix for Acer acelerometer

drivers/gpu/drm/nouveau/nouveau_drm.c
https://phabricator.endlessm.com/T15196
=> drm/nouveau: Disable runtime pm on the Asus X756UQK

drivers/net/wireless/realtek/rtlwifi/pci.c
https://phabricator.endlessm.com/T16455
=> RTL8723BE: Fix antenna selection for HP240G5

drivers/hid/Kconfig, drivers/hid/hid-asus.c
https://phabricator.endlessm.com/T14358
=> HID: asus: support backlight on USB keyboards

drivers/platform/x86/hp-wmi.c
https://phabricator.endlessm.com/T16452
=> T16452 master

drivers/platform/x86/hp-wmi.c
https://phabricator.endlessm.com/T16452
=> hp-wmi: Fix detection for dock and tablet mode

drivers/gpu/drm/amd/amdgpu/amdgpu_kms.c
Acer Aspire A515-41G and Nitro AN515-41 are not well supported even
in latest amdgpu driver. It crashes during boot so this commit disable
the amdgpu driver until there's a upstream fix.
https://phabricator.endlessm.com/T16777
=> drm/amdgpu: disable driver loading for particular Acer models

drivers/net/wireless/realtek/rtlwifi/pci.c
https://phabricator.endlessm.com/T15935
=> Quirk antenna selection on HP 240 G5/HP 250 G5

drivers/gpu/drm/amd/amdgpu/amdgpu.h, drivers/gpu/drm/amd/amdgpu/gmc_v6_0.c, drivers/gpu/drm/amd/amdgpu/gmc_v7_0.c, drivers/gpu/drm/amd/amdgpu/gmc_v8_0.c
https://phabricator.endlessm.com/T17631
=> drm/amdgpu: increase gtt size to 3GB by default v2

drivers/net/ethernet/realtek/r8169.c
https://phabricator.endlessm.com/T18107
=> r8169: Claim pmc_plt_clk_4 clock

drivers/hid/hid-rmi.c
So it looks like that suspend/resume has actually always been broken on
hid-rmi. The fact it worked was a rather silly coincidence that was
relying on the HID device to already be opened upon resume. This means
that so long as anything was reading the /dev/input/eventX node for for
an RMI device, it would suspend and resume correctly. As well, if
nothing happened to be keeping the HID device away it would shut off,
then the RMI driver would get confused on resume when it stopped
responding and explode.
So, call hid_hw_open() in rmi_post_resume() so we make sure that the
device is alive before we try talking to it.
This fixes RMI device suspend/resume over HID.
Signed-off-by: Lyude <lyude@redhat.com>
Cc: Andrew Duggan <aduggan@synaptics.com>
=> HID: rmi: Make sure the HID device is opened on resume

drivers/acpi/ec.c, drivers/acpi/internal.h, drivers/acpi/scan.c
To make media keys work on ASUS X505BA/BP, X542BA/BA, need 2 commits from upstream.
=> T17976 - port ec related fix from upstream 

drivers/gpio/gpiolib-acpi.c, drivers/pinctrl/pinctrl-amd.c
https://phabricator.endlessm.com/T17977
=>  pinctrl-amd: fix masking of GPIO interrupts 

net/rfkill/rfkill-gpio.c
https://phabricator.endlessm.com/T19284
=> net: rfkill: gpio: Add OBDA8723 ACPI HID

drivers/hid/hid-primax.c
https://phabricator.endlessm.com/T19771
=> HID: primax: fix compile error caused by last commit

drivers/pinctrl/intel/pinctrl-intel.c
The touchpad in the Asus laptop model X540NA is unresponsive
after suspend/resume. The following error appears during resume:
i2c_hid i2c-ELAN1200:00: failed to reset device.
The problem here is that i2c_hid does not notice the interrupt
being generated at this point. Because the GPIO which connects
to touchpad interrupt is in ACPI mode after resume and no longer
work as IRQ.
Fix this by saving HOSTSW_OWN register during suspend and restore
them at resume.
https://phabricator.endlessm.com/T19754
=> pinctrl: intel: save HOSTSW_OWN register over suspend/resume

include/sound/rt5651.h, include/sound/soc.h, sound/soc/codecs/rt5651.c, sound/soc/codecs/rt5651.h, sound/soc/intel/boards/bxt_da7219_max98357a.c, sound/soc/intel/boards/bytcht_da7213.c, sound/soc/intel/boards/bytcht_es8316.c, sound/soc/intel/boards/bytcht_nocodec.c, sound/soc/intel/boards/bytcr_rt5640.c, sound/soc/intel/boards/bytcr_rt5651.c, sound/soc/intel/boards/cht_bsw_max98090_ti.c, sound/soc/intel/boards/cht_bsw_rt5645.c, sound/soc/intel/boards/cht_bsw_rt5672.c, sound/soc/intel/boards/skl_nau88l25_max98357a.c, sound/soc/intel/boards/skl_nau88l25_ssm4567.c
https://phabricator.endlessm.com/T19499
=> RT5651 jack detection

drivers/net/wireless/intel/iwlwifi/iwl-trans.h, drivers/net/wireless/intel/iwlwifi/mvm/rxmq.c
https://phabricator.endlessm.com/T19756
=> T19756 - Mark MIC stripped MPDUs

drivers/acpi/acpi_lpss.c, drivers/mmc/host/sdhci-acpi.c
https://phabricator.endlessm.com/T19285
=> Improve Cherry Trail SD card compatibility

drivers/base/power/runtime.c
https://phabricator.endlessm.com/T19285
=> PM / runtime: Fix handling of suppliers with disabled runtime PM

drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c, drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c, drivers/gpu/drm/amd/display/dc/dcn10/dcn10_dpp.h, drivers/gpu/drm/amd/display/dc/dcn10/dcn10_dpp_cm.c, drivers/gpu/drm/amd/display/dc/dcn10/dcn10_hw_sequencer.c, drivers/gpu/drm/amd/display/dc/inc/hw/dpp.h
https://phabricator.endlessm.com/T20523
=> Fix problems on Raven Ridge display and resume

sound/soc/codecs/rt5651.c, sound/soc/intel/boards/bytcr_rt5651.c
https://phabricator.endlessm.com/T20855
=> rt5651: Add new quirk for DeeQ X5-Z8300

drivers/acpi/scan.c
https://phabricator.endlessm.com/T19284
=> ACPI / scan: Do not treat the OBDA8723 device as serdev for now

sound/soc/codecs/rt5645.c
https://phabricator.endlessm.com/T21052
=> EF20: rt5645: Enable quirk also for the second EF20 SKU

drivers/mfd/intel-lpss-pci.c
The ELAN1200 touchpad on ASUS X580GD (Intel(R) Core(TM) i5-8300H)
laptop run into probe fail as follows always.
i2c_hid i2c-ELAN1200:00: unexpected HID descriptor bcdVersion (0xff00)
i2c_hid: probe of i2c-ELAN1200:00 failed with error -22
However, the same touchpad on other Intel platforms work without
problems. According to the SCL signal output from oscilloscope,
the frequency of SCL is faster (around 635kHz) than expected. The
SCL high period is ~450ns, and the low period is ~1.15us. I2C fast
mode is expect to operate at 400kHz so ELAN claims the SCL high
duration is too short to read from I2C correctly. After lots of
different I2C timing parameters tested, we found what really
matters is HCNT value which causes the SCL high duration change.
This has been reported upstream, and this …
=> mfd: intel-lpss: Add new quirk for ELAN touchpad on Coffee Lake

drivers/net/wireless/realtek/rtlwifi/pci.c
This reverts commit f9cbd7e6b8226102714289bdce5488d150999cc2.
https://phabricator.endlessm.com/T22588
=> Revert "RTL8723BE: Fix antenna selection for HP laptops"

drivers/net/ethernet/realtek/r8169.c
The ethernet adapter on ASUS X441UAR does not comes back after resumes
until the MSI and MSI-X features of r8169 module in Linux 4.17.3 are
disabled.
https://phabricator.endlessm.com/T23514
=> net: r8169: Disable MSI and MSI-X for r8169 on ASUS X441UAR

sound/pci/hda/hda_intel.c
The ASUS X505ZA HDMI's audio cannot be detected until apply this quirk
which disables the power save control of snd_hda_intel module.
https://phabricator.endlessm.com/T23644
=> hda/snd_hda_intel: Disable power save control on ASUS X505ZA

drivers/gpu/drm/i915/i915_params.c, drivers/gpu/drm/i915/i915_params.h, drivers/gpu/drm/i915/icl_dsi.c, drivers/gpu/drm/i915/intel_ddi.c, drivers/gpu/drm/i915/intel_display.c, drivers/gpu/drm/i915/intel_dp.c, drivers/gpu/drm/i915/intel_drv.h, drivers/gpu/drm/i915/intel_lvds.c, drivers/gpu/drm/i915/intel_panel.c, drivers/gpu/drm/i915/vlv_dsi.c
https://phabricator.endlessm.com/T25948
=> Enable fastboot by default on VLV, CHV, and SKL or newer.

drivers/net/ethernet/realtek/r8169.c
On some boards a platform clock is used as clock for the r8169 chip,
this commit adds support for getting and enabling this clock (assuming
it has an "ether_clk" alias set on it).
This is related to commit d31fd43c0f9a ("clk: x86: Do not gate clocks
enabled by the firmware") which is a previous attempt to fix this for some
x86 boards, but this causes all Cherry Trail SoC using boards to not reach
there lowest power states when suspending.
This commit (together with an atom-pmc-clk driver commit adding the alias)
fixes things properly by making the r8169 get the clock and enable it when
it needs it.
Buglink: https://bugzilla.kernel.org/show_bug.cgi?id=193891#c102
Buglink: https://bugzilla.kernel.org/show_bug.cgi?id=196861
Cc: Johannes Stezenbach <js@sig21.net>
Cc: Carlo Caione …
=> r8169: Get and enable optional ether_clk clock

security/endlesspayg/endlesspayg.c
When the process owning the security pid dies, the pid could be reused
by another process.
Require the pidfile be held open, so we can disable all security
measures on close.
https://phabricator.endlessm.com/T27346
=> endlesspayg: disable lsm protections when pidfile closes

debian/rules.d/2-binary-arch.mk
- put the command line option eospayg in the dracut kernel command line
https://phabricator.endlessm.com/T27524
=> Endless packaging customizations

security/endlesspayg/endlesspayg.h
Brown paper bag.
https://phabricator.endlessm.com/T27046
=> endlesspayg: Add missing include file

debian.master/control.stub.in, debian/rules.d/2-binary-arch.mk
This reverts commit b3094da329c7429170db1501d3c5c1e9bfd4dba7.
https://phabricator.endlessm.com/T27042
=> Revert "Endless packaging customization"

security/endlesspayg/endlesspayg.c
Filter unauthorized access to emmc read-only controls.
https://phabricator.endlessm.com/T27048
=> endlesspayg: protect emmc ro controls

debian.master/control.stub.in, debian/rules.d/2-binary-arch.mk, debian/scripts/make_dtb_its
Deploy all device trees in a single generic FDT files.
https://phabricator.endlessm.com/T27541
=> Endless Packaging Customization

drivers/acpi/ec.c
https://phabricator.endlessm.com/T27666
=> ACPI: EC: add support for hardware-reduced systems

drivers/net/wireless/intel/iwlwifi/pcie/drv.c, drivers/net/wireless/intel/iwlwifi/pcie/trans-gen2.c, drivers/net/wireless/intel/iwlwifi/pcie/trans.c
https://phabricator.endlessm.com/T29100
=> Fix Intel Wireless 9462 WiFi regression issue in 5.4 kernel, T29100

arch/x86/Kconfig, arch/x86/include/asm/device.h, arch/x86/include/asm/pci.h, arch/x86/pci/common.c, drivers/iommu/dmar.c, drivers/iommu/intel-iommu.c, drivers/pci/controller/Kconfig, drivers/pci/controller/intel-nvme-remap.c, drivers/pci/controller/vmd.c, drivers/pci/pci.c, drivers/pci/search.c, include/linux/pci.h
https://phabricator.endlessm.com/T29119
=> intel-iommu/dmar fixups for NVMe remap

drivers/rtc/dev.c, kernel/time/ntp.c, security/endlesspayg/endlesspayg.c, security/endlesspayg/endlesspayg.h
Help prevent some problems that can occur when the hardware clock
and the system clock aren't in sync
https://phabricator.endlessm.com/T30571
=> endlesspayg: Fix rtc and system clock synchronization problems

drivers/net/wireless/realtek/rtw88/coex.c, drivers/net/wireless/realtek/rtw88/fw.c, drivers/net/wireless/realtek/rtw88/main.c
Fix BT file transfer issue for rtw88 8732de.
https://phabricator.endlessm.com/T30702
=> T30702: rtl8732de: Fix BT file transfer issue

drivers/platform/x86/asus-nb-wmi.c, drivers/platform/x86/asus-wmi.c, drivers/platform/x86/asus-wmi.h, drivers/platform/x86/intel-vbtn.c
https://phabricator.endlessm.com/T31158
=> Fix internal keyboard now working on several Asus laptops

include/linux/shmem_fs.h, mm/shmem.c
This reverts commit 97de92dbb278001bb24da58fcbf983ad294497de.
https://phabricator.endlessm.com/T13839
=> Revert "tmpfs: add user_xattr mount option"

security/endlesspayg/endlesspayg.c
https://phabricator.endlessm.com/T32959
=> [Endless] lsm: endlesspayg: Protect all threads of the LSM owner

drivers/net/wireless/mac80211_hwsim.c, net/mac80211/agg-rx.c, net/mac80211/ibss.c, net/mac80211/ieee80211_i.h, net/mac80211/mesh.c, net/mac80211/mesh_hwmp.c, net/mac80211/mesh_plink.c, net/mac80211/mesh_sync.c, net/mac80211/mlme.c, net/mac80211/rx.c, net/mac80211/scan.c, net/mac80211/tdls.c, net/mac80211/util.c, net/wireless/scan.c
Cherry picked commits from [Linux stable v5.15.74](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/net/mac80211/util.c?h=v5.15.74) to fix the WLAN security issues.
https://phabricator.endlessm.com/T33928
=> T33928: Fix various Linux Kernel WLAN security issues (RCE/DOS) found

drivers/net/wireless/mac80211_hwsim.c, net/mac80211/ieee80211_i.h, net/mac80211/mlme.c, net/mac80211/rx.c, net/mac80211/scan.c, net/mac80211/util.c, net/wireless/scan.c
Backport commits from [Linux stable v5.10.148](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=v5.10.148) to fix the WLAN security issues for EOS 4 branch.
https://phabricator.endlessm.com/T33928
=> T33928: Fix various Linux Kernel WLAN security issues (RCE/DOS) found (EOS 4)

drivers/clk/bcm/clk-raspberrypi.c
* Add support for VEC clock
* Let firmware handle some more clocks
https://phabricator.endlessm.com/T34280
=> clk-raspberrypi: fix clocks handling

debian.master/config/annotations
Enable RPi 4B related configs.
https://phabricator.endlessm.com/T34618
=> fixup! [Endless] config: Downstream customization

drivers/gpu/drm/i915/display/intel_dmc.c
Backport of upstream patch 648d7be8ecf47b0556e32550145c70db153b16fb.
https://phabricator.endlessm.com/T33858
=> drm/i915/dmc: Don't enable any pipe DMC events
